### ISSUE TITLE
Feature request: increase view distance even further

### ISSUE THREAD

**Issue by JOHN30011887** [rr-/Tomb1Main#107]
Iv noticed this for a long time with the tombati version that yes you can go to the patch file and use the two increased distance options however they still seem to have a limit where the distance is black and objects fade to black (like the attached images).

Some areas you see it bad when turning the camera, its like when you look straight on its blacked out but angle the camera to left or right and you see a bit further.

Both images have same draw distance settings. just i slightly turned on the spot
![Screenshot (14)](https://user-images.githubusercontent.com/12979984/113363566-1a6a4580-9349-11eb-9922-e7d71aea19c4.png)
![Screenshot (13)](https://user-images.githubusercontent.com/12979984/113363588-25bd7100-9349-11eb-8d1f-5f177fb9a8a9.png)

Putting anything above "draw_distance_fade = 73728" and "draw_distance_max = 81920" doesn't seem to work so i guess those numbers are the max that was chosen in the patch file.

Would be great if we could have better option to greatly increase distance please :)

**Comment by rr-** [comment]
Implemented in 1.4.0.
