### ISSUE TITLE
use ALL of the features!!

### ISSUE THREAD

**Issue by TommvinHuwaltzky** [rr-/Tomb1Main#108]
Hey, 
realy like your mod and the things it adds. But would it be possible to use this alongside, or merge/combine with, the [Automated Fix](https://github.com/Carlmundo/TombRaider-AutomatedFix)?
It has a lot of options your fix doesn't, but also lacks stuff that you brought to the table and that, honestly, should be together. If I install one I miss features from the other.
Well, just lemme know what you think (:

Cheers

**Comment by rr-** [comment]
Please make a separate feature request for each functionality that you're missing.
