### ISSUE TITLE
Underwater caustics move at 2x speed

### ISSUE THREAD

**Issue by Raildex** [rr-/Tomb1Main#109]
In my opinion, the underwater caustics/flickering is a bit too fast.
It would be great to have a customizable frequency (in frames?)

**Comment by walkawayy** [comment]
@Richard-L could you record a video of Lara just sitting in the water on PS1? I think rr is right that the water wibble is way too fast.

**Comment by Richard-L** [comment]
After some exchange with walkaway:

https://user-images.githubusercontent.com/4934209/163011979-3f86cf23-a9c5-46bd-a841-2d88f80a5de4.mp4



https://user-images.githubusercontent.com/4934209/163012570-124d54b7-85c0-4d74-92c4-841f3ad5a0df.mp4



It's easy to see the underwater effects are too fast, as @Raildex already observed.

Personally I would not make this configurable. I would set one "correct" pace for this effect that's as close to PS1 as possible. Currently it seems to be twice as fast (?)

For reference, TombATI (old DOS purple water) seems to have the identical speed:

https://user-images.githubusercontent.com/4934209/163014452-4100957d-881a-4cfb-84b6-a7ed1fdba4fd.mp4

**Comment by Richard-L** [comment]
https://user-images.githubusercontent.com/4934209/163168741-980caca9-02f2-4e5c-b08b-29bedc991391.mp4

I tried to sync the caustics animation frame-exact between both videos, but it was a bit too much of a process. Still, I think it's very easy to see that the animation loop syncs perfectly now :thumbsup:

This solves this issue in my eyes.

However, this made me notice two things about the water surface. One is #126, and two is the animated texture. If you compare you can see it's faster on PS1, and I daresay more... varied? @walkawayy should this at all be related to `ticks - 1`?

**Comment by walkawayy** [comment]
I think this is now correct.

https://streamable.com/91auce

**Comment by Richard-L** [comment]
Perfect :ok_hand:
