### ISSUE TITLE
T1M bug: bars placed in the same corner overlap with each other

### ISSUE THREAD

**Issue by Raildex** [rr-/Tomb1Main#111]
Having Two bars in one corner makes them overlap and you can only see one bar.
Either offset Bars automatically or give the option to change the Y position.

**Comment by rr-** [comment]
T1M has code to target this issue specifically; I'm surprised to hear that it's not working.

**Comment by Raildex** [comment]
@rr- My bad, I was falling in the water and didn't realize the health bar disappears. (Air bar is in the position of health bar then)

But. On lower resolution they do overlap:
![screenshot0003](https://user-images.githubusercontent.com/14938934/113746531-b8259200-9706-11eb-98dc-dd69f01008b4.jpg)

**Comment by walkawayy** [comment]
I think this is solved thanks to aa55d9d.
