### ISSUE TITLE
OG Bugfix: Stacked rooms allow climb ledge onto wall

### ISSUE THREAD

**Issue by Raildex** [rr-/Tomb1Main#115]
When you have 2 rooms stacked, where the upper room has a ledge and the lower room has a wall, Lara can climb into the wall when she climbs leftwards.
This is an original TR1 Bug and appears in St. Francis Folly. For demonstration I made a Level with TE.
This is NOT an "invisible ledge" where ceiling/floor are on the same height. It is an actual wall sector!

[Video](https://streamable.com/h3ygdn)

[St. Francis Folly](https://streamable.com/d46uia)

**Comment by Raildex** [comment]
Here is the test level
[LEVEL1.zip](https://github.com/rr-/Tomb1Main/files/6269890/LEVEL1.zip)

**Comment by rr-** [comment]
@walkawayy could you please have a look if your / EdisonEngine drawbridge fix could be used to fix this issue? :)

**Comment by walkawayy** [comment]
@Raildex the videos must have deleted for being too old. Could you screenshot the location to test?

**Comment by walkawayy** [comment]
Here's the St. Francis Folly example:
![image](https://user-images.githubusercontent.com/81546780/146647025-631d4153-fb57-4281-911b-78ed061c1681.png)

**Comment by walkawayy** [comment]
Well I ported TR5's `LaraHangTest` and it's fixed... mostly. 😢 

https://streamable.com/zkaiaf

**Comment by rr-** [comment]
Looks good enough to me :)

**Comment by walkawayy** [comment]
it breaks this hang and grab in Natla's Mines... I'll have to keep working on it.

![image](https://user-images.githubusercontent.com/81546780/146656214-bb46147c-87e3-4553-a1bd-59afb5d3dc5f.png)

**Comment by walkawayy** [comment]
Ok I think I got it working! Gonna ask around for more weird spots to check to make sure I didn't break anything else. I pared down the changes from TR5. Basically there just needed to be an extra `SLOPE_DIF > hdif > -SLOPE_DIF` check in the stop condition of `LaraHangTest`.

https://streamable.com/i1ezxh

**Comment by walkawayy** [comment]
Now Lara can't shimmy on one side of this walkway but can on the other. Really odd.

https://streamable.com/y5m9qm

**Comment by walkawayy** [comment]
Alright I took out the ceiling check, leaving the `hdif` checks as the only new checks. That seems to work. I tested on a LOT of ledges in St. Francis Folly and didn't find any issues.
