### ISSUE TITLE
no building documentation

### ISSUE THREAD

**Issue by oziphantom** [rr-/Tomb1Main#120]
So after trying msys2 on a windows vm that I had, running into the problem that it needed a python json parser, and that needed pip, which doesn't give with msys and spending 4 hrs to which I eventually had to uninstall msys2, reinstall it so I could get PIP to work, only to watch pyJSON5 fail to compile because it needed the Crypt.h. After finding and install the library that should give it to me, it would still fail to compile the json parser. 

I have to ask at this point does this really need an external json parser that needs CPython and wheels for 1 file that won't be over 1K for a single for loop based operation? 

So then I spot docker, vaguely heard of and and know what it does, lets give that a shot.. fire up actual linux vm, its out of date and beyond life, so download iso and install fresh again. Install docker, work out how to get it to run your config file. 
So after a full day, I can get it to run make( build cmd doesn't work and it gives an error), however I can't see any file output from it, there is no dll file in the build directory. 

So could you make a "how to build, run and debug" this for a windows game developer using a linux vm to handle your development pipeline for somebody who doesn't use linux for development? Or even some base line how to build that I can point to somebody who does to translate for me?

**Comment by rr-** [comment]
Hi, FYI this post feels more like a rant rather than an actual issue report.

The documentation, although scarce, is here:

https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md

You don't need a Linux virtual machine, you can use WSL. Start WSL, paste the commands and it should build.

**Comment by oziphantom** [comment]
Rant - fair, I can't argue. 

So 'cfg' folder needs to be copied into the same folder as the tombati.exe?

After building do you need to copy the dll and the exe or just the dll?

Should the Tomb1Main.json5 file be updated for the build and copied, or do you just need to update it in the cfg file that is with the running exe or just in the build cfg file?

Is the code building release or debug? is there a way to get a pdb file so one can attach a debugger to the running instance? or do you have a debug channel one can printf debug with?

What are you using to de-compile the remaining functions? Ghidra? 


After seeing Cygwin and Msys totally destroy windows installs, today as case in point where it stuffed up the VM to the point that shutting down the machine actually causes VirtualBox to crash and I had to do some rebuilding of it, I don't let posix things have free reign on my windows machines. It needs to live inside a fully contained box where it can be nuked when it goes wrong.

**Comment by rr-** [comment]
>So 'cfg' folder needs to be copied into the same folder as the tombati.exe?

Yes, once

>After building do you need to copy the dll and the exe or just the dll?

Just the DLL

>Should the Tomb1Main.json5 file be updated for the build and copied, or do you just need to update it in the cfg file that is with the running exe or just in the build cfg file?

You only need to update it if you make changes to the configuration, e.g. introduce a new option.

>Is the code building release or debug? is there a way to get a pdb file so one can attach a debugger to the running instance? or do you have a debug channel one can printf debug with?

See `Makefile` which is made by hand for simplicity (I dislike C ecosystem because of experiences similar to yours), `make debug` makes a `-g` build, whereas `make` should make a normal unoptimized build.

>What are you using to de-compile the remaining functions? Ghidra?

IDA Pro.

>After seeing Cygwin and Msys totally destroy windows installs, today as case in point where it stuffed up the VM to the point that shutting down the machine actually causes VirtualBox to crash and I had to do some rebuilding of it, I don't let posix things have free reign on my windows machines. It needs to live inside a fully contained box where it can be nuked when it goes wrong.

That's what the Docker builds are for. 
When I doubt you can also see how GitHub actions are configured by seeing `.github/workflows/release.yml` file.

**Comment by oziphantom** [comment]
Don't get me wrong, I'm a game dev from the era, I love C and C++ just like every other game dev I use Visual Studio, especially when making a windows only game with a windows only DLL using Microsoft Direct Technologies :D I did manage to get the dll to build in VS only I get 'Not a valid executable file' when I run the exe after making it.. Doesn't even seem to open the log.. 

In order for docker on windows to build with gcc you would still need to have a linux system installed into it right? or does Docker make that it self and keep the windows pure? 

Do you know where the function that decides which direction Lara should move relative to the camera is? I want to fix the camera swings and you run into a wall, but I can't find any code the mention input, camera and lara at the same time. Since the translate function uses y_rot I assumed it was picking up something from the camera but I also can't see anything that is modifying the y_rot of Lara. There is the Lara.turn_rate but I also can't see anything that looks at a camera and modifies it either. 

Do you know what PHD stands for in this context? 

Are all int16_t f8p8? and are all uint32_t f16p16 in the graphics and positions system? or does it have other splits as well?

**Comment by rr-** [comment]
>In order for docker on windows to build with gcc you would still need to have a linux system installed into it right? or does Docker make that it self and keep the windows pure?

When I mention WSL I mean "Windows Subsystem For Linux" a feature that Windows system has since long ago. You run Linux on your Windows, and it's not a virtual machine – it's a layer of transaction between Linux kernel kalls to Windows kernel calls. You enable this feature from Control Panel, quite literally. I don't know what you mean by "pure" Windows, installing Docker also means a dependency.

The reason why I didn't go with Microsoft Visual Studio, MSYS or anything is because 
1) I simply don't have time or energy to deal with another build system that only works on Windows
2) I want GitHub actions to make new builds automatically and the best supported OS here is Linux
3) I don't own Visual Studio, and I don't want a Microsoft Account, honestly I think it's bonkers to require signing up somewhere to write some C code

>Do you know what PHD stands for in this context?

PHD is the initials of the Tomb Raider's original programmer, Paul H. Douglas

>Do you know where the function that decides which direction Lara should move relative to the camera is?

The entire camera logic is in `game/camera.c`. The only exception are camera triggers that are covered in `game/control.c` under `TO_CAMERA` switch case.

>Are all int16_t f8p8? and are all uint32_t f16p16 in the graphics and positions system? or does it have other splits as well?

I am not familiar with this notation. They're 16-bit and 32-bit little-endian integers respectively. In terms of geometry one tile means 1000 units. In terms of angles one turn equals 65535. Core Design avoided floating point arithmetic to achieve tolerable performance on PlayStation 1.

**Comment by oziphantom** [comment]
> 
> 
> > In order for docker on windows to build with gcc you would still need to have a linux system installed into it right? or does Docker make that it self and keep the windows pure?
> 
> When I mention WSL I mean "Windows Subsystem For Linux" a feature that Windows system has since long ago. You run Linux on your Windows, and it's not a virtual machine – it's a layer of translation between Linux kernel calls to Windows kernel calls. You enable this feature from Control Panel, quite literally. I don't know what you mean by "pure" Windows, installing Docker also means a dependency.
> 
> The reason why I didn't go with Microsoft Visual Studio, MSYS or anything is because
> 
>     1. I simply don't have time or energy to deal with another build system that only works on Windows
> 
>     2. I want GitHub actions to make new builds automatically and the best supported OS here is Linux
> 
>     3. I don't own Visual Studio, and I don't want a Microsoft Account, honestly I think it's bonkers to require signing up somewhere to write some C code
> 
> 
By "pure" I mean I don't have any POSIX based side systems, sub systems or translation systems install and running within Windows(or any other OSes for that mater). Be it MSYS, Cygwin, WSL or WSL2. Typically when I have a smaller "needs POSIX" I pull out a Raspberry Pi and "Air gap" it, but for this case not so practical so I fire up a Virtual Machine.

> > Do you know what PHD stands for in this context?
> 
> PHD is the initials of the Tomb Raider's original programmer, Paul H. Douglas
Oh yeah, slaps forehead. 
> 
> > Do you know where the function that decides which direction Lara should move relative to the camera is?
> 
> The entire camera logic is in `game/camera.c`. The only exception are camera triggers that are covered in `game/control.c` under `TO_CAMERA` switch case.
> 
Hmm in Camera.c:560-584 there is code that changes the Lara.head and lara.torso_r_rot which is not the LaraItem rotation but a good source to start tracking. Thank you, I missed that earlier. 

> > Are all int16_t f8p8? and are all uint32_t f16p16 in the graphics and positions system? or does it have other splits as well?
> 
> I am not familiar with this notation. They're 16-bit and 32-bit little-endian integers respectively. In terms of geometry one tile means 1000 units. In terms of angles one turn equals 65536 units. Core Design avoided floating point arithmetic to achieve tolerable performance on PlayStation 1.

Fixed Point notation. i.e the 16bits is actually 8bits.8bits rather than a floating point where the number of bits before and after the . changes you use a fixed point and hence all the maths drops back to ints, Only when multiply you then have to shift it back because the numbers get squared. 
so given a 16bit f8p8 you have
0x0100 = 1
0x0180 = 1.5
0x0240 = 2.25 

It's actually a Saturn game, that is why the world is built out of Quads and not triangles, as a Saturn can't draw triangles in hardware.

**Comment by oziphantom** [comment]
Ok, After looking some more and doing some testing with keyboard mode, I'm now convinced the issue is not the game using forward of the camera for each move but more the way the Steam Overlay maps the Analogue stick to the dpad movement. I've added Joystick support to the game, where I've done a better mapping and I no longer run into walls. 

For these feature I think people will expect it to the user configurable, however you have to also select which input type you want, for example the dpad is a Hat on the XBox Controller and the L and R triggers are a Z axis. Have you given any though to how you would implement said feature?
