### ISSUE TITLE
Can't open file after download and extract

### ISSUE THREAD

**Issue by REF-2021** [rr-/Tomb1Main#121]
Hi! I've followed the download and extract of Tomb1Main as per the instructions (download TOMBATI first, then extract and replace files with TOMB1Main. However, whereas TOMBATI opens before I replace it, it does not after I have replaced it with Tomb1Main files. Can you help please?

**Comment by thatguyfrombb** [comment]
Hi! Does it give an error? Post it here. Did you extract all files from the ZIP, not just the EXE? All of them are needed for Tomb1Main to work. Do you get a file named Tomb1Main.log? If so, post it here too.

**Comment by REF-2021** [comment]
It doesn't give an error, it just opens and then automatically closes. And there doesn't appear to be a file named Tomb1Main.log in the ATI folder that I extracted it too. I extracted all of the files from this ZIP (uploaded). Should I have downloaded some extras? 
[Tomb1Main-1.1.3 (3).zip](https://github.com/rr-/Tomb1Main/files/7253733/Tomb1Main-1.1.3.3.zip)

[readme.txt](https://github.com/rr-/Tomb1Main/files/7253715/readme.txt)
[Tomb1Main.log](https://github.com/rr-/Tomb1Main/files/7253716/Tomb1Main.log)
[Tombraider.txt](https://github.com/rr-/Tomb1Main/files/7253717/Tombraider.txt)

**Comment by REF-2021** [comment]
Ah, there is a .log!

**Comment by thatguyfrombb** [comment]
Ok, so it does start loading the FMV, but it doesn't show it for some reason. Could you temporarily rename your FMV folder to something else so it doesn't load it and retry?

**Comment by REF-2021** [comment]
I renamed the folder from FMV to 'Rename' but the same thing happens: It just shows a blank screen for two seconds and then automatically closes...

**Comment by thatguyfrombb** [comment]
Post the log file on every update, please :) That's the way Tomb1Main will talk to us.

**Comment by REF-2021** [comment]
Oh, sorry! Here it is
[Tomb1Main.log](https://github.com/rr-/Tomb1Main/files/7254036/Tomb1Main.log)

**Comment by thatguyfrombb** [comment]
FMVs are not the issue then :) I think your GPU is not getting properly detected/initialized by Tomb1Main. What hardware do you have?

- Is it a desktop or a laptop?
- What is your CPU?
- What is your graphics card(s)?
- How many monitors do you have and which resolution are you using on each of them? Which is the primary?

**Comment by REF-2021** [comment]
Thank you ever so much for helping me, I really appreciate it!

Laptop
CPU: Intel(R) Core(TM) i3-2350MCPU @ 2.30GHz (4CPUs)
Graphics card: Intel(R) HDGraphics 3000
1 monitor, resolution: 1366 x 768
Hopefully I've given you the right information!

**Comment by thatguyfrombb** [comment]
No problem. Thanks for reporting your issue :)

I have a system that is very similar, although not the same, so I'll give it a try myself. One thing I forgot is your OS. Windows 10 x64 I assume?

**Comment by REF-2021** [comment]
Thanks very much! Yes, Windows 10 x64 :)

**Comment by thatguyfrombb** [comment]
Sorry about the wait. The PC I needed to use was giving me some problems. I just tested it and it acts exactly like yours, so the GPU is the issue. I'll see if I can find a fix. Anyway, there's plans to change the renderer, which _should_ make it all work again, but I'm nobody to give a timeframe on that.

Thank you for the report. I'll keep this updated if I find something, either a reason why it happens or a fix.

**Comment by REF-2021** [comment]
No worries, and thank you for your help so far! I'm relieved that it's not just me being silly. Thank you for keeping me updated.

**Comment by thatguyfrombb** [comment]
It's been a long time. Tomb1Main is now on version 1.2.0 and there have been some important updates that relate to this. I can confirm that it works on my 2nd gen Intel system, @REF-2021, could you test with the new version and report back?

**Comment by rr-** [comment]
Slow startup will be less of an issue when we have a standalone .exe. Thanks
