### ISSUE TITLE
Default jump key (Alt) brings up window menu

### ISSUE THREAD

**Issue by MatthTheGeek** [rr-/Tomb1Main#122]
The default jump key (Alt) pauses the game (by losing focus) and brings up the window menu.
![Capture1](https://user-images.githubusercontent.com/28271613/136692663-9eb9b04b-4acc-4061-ac7f-ac9b34ed38b1.PNG)
 
This behaviour was not present with the original tombati

**Comment by oziphantom** [comment]
so turns out you can get this into window mode, so I guess you are running this in windowed mode? 
On mine the Alt halts the game but doesn't bring up the menu.

**Comment by rr-** [comment]
> @rr- I can't be bothered to do a whole new branch for this so I can submit it as a pull request
> 
> smain.c : 165 add
> 
> ```
> 
> case WM_SYSCOMMAND:
>        // did they just press ALT
>        if (wParam == SC_KEYMENU && (lParam >> 16) <= 0) {
>             return 0; //ignore it, stops menu from opening
>        } else {
>            return DefWindowProcA(hWnd, uMsg, wParam, lParam);
>        }
> ```

I don't understand what's the problem with adding a PR?

**Comment by oziphantom** [comment]
I would have to switch back to master, make a new branch off master, which will put me back into linux build, add the patch on linux, test that it works, then copy the code back to windows, check it in, then send you a pr, then switch back to my branch.  for 7 lines ...

yes ALT+ENTER still works. I just disables the KEYMENU command not any other system commands, so ALT+F4 still works as well

**Comment by oziphantom** [comment]
standard Windows hotkey : Alt + Return ( also called Enter on US keyboards, but its the one above shift not the one in the numpad )

**Comment by rr-** [comment]
Fixed in 1.2.0, if there are issues please post here and I'll reopen the ticket

**Comment by MatthTheGeek** [comment]
Can confirmed this is now fixed. Much appreciated :)
