### ISSUE TITLE
Release 1.1.4 crashes

### ISSUE THREAD

**Issue by pcblizzard** [rr-/Tomb1Main#123]
Release 1.1.4 crashes reproducibly after the last intro video (after that comes the main menu, which you can no longer see).

Release 1.1.3, however, works without any problems

**Comment by oziphantom** [comment]
undid the Gun typo check in as well, still crashes;.

my fork was based upon the Mar 31 code. Thus the difference between my 60fps and this "pure" build is the "fix gcc warnings" check-in on the 1st Sept.
