### ISSUE TITLE
OG bug: bat height

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#129]
Maybe just something to capture for later. Apparently hanging bats that aren't flying yet are positioned too high in the PC version, so that they're sometimes hidden by the ceiling.

TombATI/TR1Main
![](https://cdn.discordapp.com/attachments/811974815672959046/898684956824453140/unknown.png)

PS1
![](https://cdn.discordapp.com/attachments/811974815672959046/898685065922478120/unknown.png)

In fact this can sometimes create some artefacts in TR1Main. Bat coming through next to her left foot here:

https://user-images.githubusercontent.com/4934209/137557520-fbd8f07d-7b5c-4646-aa2b-90552aa2899d.mp4

**Comment by oziphantom** [comment]
are they in the wrong position or is this a manifestation of the sorting bug?

**Comment by rr-** [comment]
According to Troye they're in a wrong position.
