### ISSUE TITLE
OG bugfix: Make the game remember controls type choice

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#13]
When you have User Keys controls customized, it only supress default bindings when User Keys mode is selected. Each time you start the game, default bindings is placed first.

For example, you bind Jump for Space button. When User Keys is selected, Lara will jump with Space. If you restart the game and ignore Contols page, Lara will Jump with Space and also draw/undraw her weapons at the same time. User Keys mode has to be selected manually every time the game started to work properly.

**Comment by Defrago** [comment]
With 0.12.2 this behavior still applies: `For example, you bind Jump for Space button. When User Keys is selected, Lara will jump with Space. If you restart the game and ignore Contols page, Lara will Jump with Space and also draw/undraw her weapons at the same time. User Keys mode has to be selected manually every time the game started to work properly`

But now you don't have to pick User Keys mode. Just visiting Controls page fixes the problem described above

**Comment by rr-** [comment]
Very interesting
