### ISSUE TITLE
Incorrect ingame resolution (High DPI related?)

### ISSUE THREAD

**Issue by annlyt** [rr-/Tomb1Main#130]
![Desktop Screenshot 2021 10 16 - 10 14 38 69](https://user-images.githubusercontent.com/13076939/137582927-0922819b-9ea5-47e6-b578-4867d3bc9fc2.png)

Upon entering a game, resolution is wrong. Title screen is unaffected and looks correct.

I has something to do with HWR_SwitchResolution and it might be High DPI related as I use a 4K TV as my monitor.

I tried turning on high dpi in the exe properties but no change.

**Comment by rr-** [comment]
What's your configuration option in the (now ignored) option `context.fullscreen_virtual` in tombati settings?

**Comment by rr-** [comment]
And `patch.resolution_width` while we're at it

**Comment by annlyt** [comment]
> 
> 
> And `patch.resolution_width` while we're at it

resolution_width = 1440

**Comment by annlyt** [comment]
I'm still forced to use 4K with the fix and with DPI off I'm forced to use 720p. I want to set my resolution to 1440p or 1080p but I cannot.

![Desktop Screenshot 2021 10 17 - 10 10 54 38](https://user-images.githubusercontent.com/13076939/137620555-9eac27d8-30c7-4725-875d-48c79b97d3ec.png)

![Desktop Screenshot 2021 10 17 - 10 07 40 38](https://user-images.githubusercontent.com/13076939/137620557-8f46a57b-0817-4665-bf81-de10baa33608.png)

![Desktop Screenshot 2021 10 17 - 10 08 17 18](https://user-images.githubusercontent.com/13076939/137620558-ffe8478d-4032-41f6-8938-3e3c55eae8a1.png)

**Comment by rr-** [comment]
See `resolution_width` and `resolution_height` in the config file. @annlyt

**Comment by annlyt** [comment]
Repaired

Replace this line: https://github.com/rr-/Tomb1Main/blob/f29c6ee8f7c8f11cb17381aff1f8d4d53fddf42f/src/global/vars.c#L117

with this:
    { 320, 200 }, { 512, 384 }, { 640, 480 }, { 800, 600 }, { 1024, 768 }, { 1280, 720 }, { 1920, 1080 }, { 2560, 1440 }, { 3840, 2160 }, { 4096, 2160 }, { 7680, 4320 },  { -1, -1 },

And this line: https://github.com/rr-/Tomb1Main/blob/f29c6ee8f7c8f11cb17381aff1f8d4d53fddf42f/src/global/const.h#L223

Change 5 to 12.

![tombati60FPS 2021-10-17 11-58-54 original](https://user-images.githubusercontent.com/13076939/137625008-f006973f-44aa-4ac6-b315-678577ed4164.jpg)

Now works correctly with High DPI screens.

**Comment by rr-** [comment]
Please override the `resolution_width` and `resolution_height` like I told you.

**Comment by annlyt** [comment]
Thx rr-
