### ISSUE TITLE
OG bug: faulty coliseum textures

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#131]
Infamous Midas textures incorrectly showing at the top of the coliseum. SuikazeRaider had created a fix for these in one of his projects: ![](https://cdn.discordapp.com/attachments/295218582940286990/830770494344396830/level5_fix_001.jpg)

Discord source: https://discord.com/channels/218414493355606016/295218582940286990/830770497100841010

**Comment by atombraiderfan** [comment]
I wonder if using a texture pack would be the answer to this issue, but that depends on #347 getting done first.

I read [here](https://trtranslationsworld.wordpress.com/author/suikazeraider/) that the correct midas texture was found on the beta version of TR1.

**Comment by Richard-L** [comment]
@atombraiderfan nice link! I remember SuikazeRaider telling me about the beta but I'd forgotten. The guy is such a treasure trove of classic TR knowledge, it's incredible.

I would be much happier if this was "just a fix" instead of a custom texture situation, but either way, any fix is good.

@rapora when you inspect the level, is there any indication perhaps why these textures were misaligned?
