### ISSUE TITLE
T1M bug: (master) Black screen after inventory with FPS counter on

### ISSUE THREAD

**Issue by thatguyfrombb** [rr-/Tomb1Main#158]
Passport>New game>New game. F2, FPS counter displays. Press ESC twice and screen goes pretty much black.

It doesn't happen on latest release.

![BlackScreenSmall](https://user-images.githubusercontent.com/11382298/139604407-741a84da-6fec-4458-8c04-f1e14124de7e.png)

[Tomb1Main_BlackScreen.log](https://github.com/rr-/Tomb1Main/files/7449918/Tomb1Main_BlackScreen.log)

**Comment by rr-** [comment]
I'll investigate it tomorrow before we go with #156
