### ISSUE TITLE
OG Bugfix: sidestep descending bug

### ISSUE THREAD

**Issue by Trxyebeep** [rr-/Tomb1Main#163]
Original bug:
https://www.youtube.com/watch?v=qfNIx3FEgtw

The fix would be to implement the "LaraFallen" function.
LaraFallen:
https://github.com/Trxyebeep/TOMB5/blob/master/TOMB5/game/lara.cpp#L1009
^ and searching for "LaraFallen" in that page shows where the needed checks are

**Comment by rr-** [comment]
Turns out you can also walk backwards to trigger it
