### ISSUE TITLE
OG bugfix: wallbugs and jumping through objects

### ISSUE THREAD

**Issue by Trxyebeep** [rr-/Tomb1Main#165]
wallbug is when you jump at a wall and Lara teleports to the top of it:
[https://youtu.be/Y3vAg4eaxY4?t=31](url)
The floor has to be slopes, thus being called the "slope bug" in a  few places.

jumping through objects is the infamous glitch of making continuous running jumps at an object, making Lara inch into it slowly, until she pops out the other side.

Both of these bugs can be solved by removing the call to AnimateLara from LaraColForwardJump.
[https://github.com/rr-/Tomb1Main/blob/master/src/game/lara.c#L1113](url)

However: there is one disadvantage to removing this call: a barely noticeable 1 frame delay in Lara's landing animation.

Tomb Raider Chronicles had this call removed, here is a video attempting to showcase the frame delay:
https://user-images.githubusercontent.com/38836940/139750978-dc7a710b-ecf1-4d66-96eb-820687708bb3.mp4

**Comment by vvs-** [comment]
I have enabled fix for that and it seems that it doesn't actually work. At least I was able to go through grating (running, rolling or jumping, no matter) in the sphinx room of the first level of UB. This happened in the corner of the grating. Or is this another glitch?

**Comment by rr-** [comment]
cc @Trxyebeep
