### ISSUE TITLE
OG bugfix: Fix Larson in Qualopec cinematic

### ISSUE THREAD

**Issue by thatguyfrombb** [rr-/Tomb1Main#167]
Larson's left arm clips through his sleeve. Also, his right arm moves inside his leg.

Footage from some DOS version (matches what I'm seeing in TombATI and T1M), left arm clipping visible since ~7:58, right arm goes inside leg at ~8:22:
https://youtu.be/vr104HV7wg0?t=479

The PSX version has it's own share of clipping issues, and it still moves the right arm inside the leg:
https://youtu.be/AH3u5CQRKKA?t=506

**Comment by rr-** [comment]
I'm not sure how to fix those issues, I mean the polys do go inside each other in that animation.

**Comment by oziphantom** [comment]
Cinematics have fixed animations for each object, to fix this would require changing the animation data in the phd files. Not a code fix.

**Comment by thatguyfrombb** [comment]
Give me a couple days to think about it.

**Comment by Richard-L** [comment]
https://user-images.githubusercontent.com/4934209/139953951-8d16b6af-6e64-4cb4-9181-3a5782ae1707.mp4

fwiw, this is what it looks like with Duckstation's experimental "Depth Buffer" feature. Similar to PC I'd say.

(NB the scene desyncs because this is the PAL version sped up to 60hz timings, which works in game for correct speed and 30fps, but not during the cutscenes.)

**Comment by thatguyfrombb** [comment]
Update: Can be done but could be awful.

Cinematics are levels which (among other stuff) contain actors (like Larson) as objects and their movements as a single animation per actor. So, once we load this level, we can access the frames for these animations and edit them, by adding or substracting from their packed rotations.

Two issues with this: Smooth movements and storage. If we want to make "simple" commands, added movements would start and stop suddenly. On storage, we need to store these changes somewhere, and it has to change per level. Considering what we have right now, the gameflow file would be the best fit, and I'm not sure I'd like that...

**Comment by rr-** [comment]
Let's not go there. If someone needs it, they can edit cut1.phd by hand. Which we cannot ship anyway because of legal reasons. And having an installer that fixes only this particular issue… IDK, there are too many things that can go wrong IMO.

**Comment by rr-** [comment]
Also some people might be disappointed to learn Larson no longer reaches for his crotch in that cutscene.

**Comment by Richard-L** [comment]
I tend to agree it's fine to leave as is

**Comment by rr-** [comment]
Closing as won't fix because I don't think there's much we can do. If someone suggests a good fix in the future, I'm happy to revisit this issue.
