### ISSUE TITLE
Feature request: increase number of save slots

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#170]
Would be nice to have at least two per level I'd say.

**Comment by oziphantom** [comment]
I further this motion and will probably drop a surprise PR with it.

**Comment by fluxtom** [comment]
Had a brief look into this.

Simply increasing the number of save slots is easy. There is the [MAX_SAVE_SLOTS](https://github.com/rr-/Tomb1Main/blob/db9c32c7f2fd41cb2fff1a5ba4fee7a8280267ac/src/global/const.h#L29) constant, changing this number seems to do everything (listing every save slot to that number, saving to any slot, loading from any slot). I can make a PR with this changed, not sure the best number though.

I then tried figuring out making this configurable which seems to require a lot of dynamic memory allocation. I might try and give it a go even if it doesn't get merged in, if for nothing else than to practice dynamic memory.
