### ISSUE TITLE
Consider making optimized releases

### ISSUE THREAD

**Issue by thatguyfrombb** [rr-/Tomb1Main#179]
While I think it might be too soon for this yet, there's lots of performance to be gained by compiling with `-O2`. For an old PC (Phenom II x4 965, GeForce GT710) it makes the difference in being able to run at 1920x1080 at a constant 30fps.

Con: Harder debugging on releases, as the assembly won't match as much.

Again, too soon, we still have dependencies on the original EXE and lots of pointers and casts being thrown around. Just something to consider.

**Comment by oziphantom** [comment]
oddly I find Clang doesn't know how to not optimise the code, I keep getting variables not found in the debugger even then I've set it to disable optimistaion.

**Comment by rr-** [comment]
I think we're ready.

Fixed in 02e7741e5a16ca02435243a2cca64b225950c116
