### ISSUE TITLE
Feature Request: Add Lara's Animations from tr2-5

### ISSUE THREAD

**Issue by Kubsy** [rr-/Tomb1Main#181]
As the title suggests, I think there should be some Lara's animations that aren't in TR1 for example: MonkeySwing, ladders, crawlspace etc.

This would probably increase gameplay ideas for TRLE custom levels.

**Comment by rr-** [comment]
Too much effort. Same with bringing flares. I don't see the point of making T1M becoming Tomb Raider 2, 3, 4 or 5.
