### ISSUE TITLE
Software request: Level Converter

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#188]
There is considerable amount of prerelease, demo and regional versions of levels, including other platforms ones which currently can't be played with Tomb1Main project. OpenLara project by @XProger has implementations of some of the formats described above. After Discord discussion we concluded that there would be better to create a separate level converter rather than expand Tomb1Main codebase with additional versions of levels reading.

So I propose to create a converter for the levels from PS1, Saturn, Demo and Prerelease formats to T1M PC ones. As for demos, there should be an option to disable level end trigger to allow more exploration.

**Comment by rr-** [comment]
Continued in https://github.com/rr-/Tomb1Main/discussions/247
