### ISSUE TITLE
Feature request: ability to open doors with cheat

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#19]
Make ability to open/close doors with cheats

Possible way of doing that: allowing weapons using in DOZY. Hitting the door makes it open/close

**Comment by Defrago** [comment]
Great feature. Opened some doors that I never been able too.

Yet there is still area for improvements. Some doors currently still can't be open. You also can't open trapdoors and draw bridges. Ability to close/lower them would also be nice.

![Снимок (8)](https://user-images.githubusercontent.com/25227941/110209380-5bcc1a00-7e9d-11eb-9a70-b5267201a26b.png)
![Снимок (1)](https://user-images.githubusercontent.com/25227941/110209400-6dadbd00-7e9d-11eb-9f47-c0ad4a6276ce.png)

**Comment by Defrago** [comment]
With that code from ChocolateFan it's possible to open doors current implementation can't. Mostly those that is closed by trigger after Lara passing them. I used it as separate function since I'm not truly understanding the code.

`{
    int16_t best_door = NO_ITEM;
    int32_t best_dist = 0x7FFFFFFF;
    int32_t max_dist = WALL_L * 2;

    for (int item_num = 0; item_num < LevelItemCount; item_num++) {
        ITEM_INFO *item = &Items[item_num];
        int32_t x = (item->pos.x - lara_item->pos.x) >> 8;
        int32_t y = (item->pos.y - lara_item->pos.y) >> 8;
        int32_t z = (item->pos.z - lara_item->pos.z) >> 8;
        int32_t dist = SQUARE(x) + SQUARE(y) + SQUARE(z);
        TRACE("found item %d: dist=%d", item_num, dist);
        if (item->object_number >= O_DOOR_TYPE1
            && item->object_number <= O_DOOR_TYPE8) {
            TRACE("found door %d: dist=%d", item_num, dist);
            if (dist < best_dist) {
                best_door = item_num;
                best_dist = dist;
            }
        }
    }

    if (best_door == NO_ITEM || best_dist >= SQUARE(max_dist >> 8)) {
        return;
    }

    ITEM_INFO *item = &Items[best_door];
    if (1) {
        item->touch_bits = 0;
        item->flags |= IF_CODE_BITS;
        item->timer = 0;
    }
}`

More examples of doors you can't interact with both functions added
![Снимок (14)](https://user-images.githubusercontent.com/25227941/110332508-7505cf80-8031-11eb-9fcc-811733d20404.png)
![Снимок (13)](https://user-images.githubusercontent.com/25227941/110332518-76cf9300-8031-11eb-9d74-51f024fcd125.png)
![Atlantis](https://user-images.githubusercontent.com/25227941/110332521-77682980-8031-11eb-80d5-9b879eeb46ae.png)

**Comment by Defrago** [comment]
Open/Close cheat works great. So far I found no door/trapdoor I couldn't interact with (haven't check them all yet), but now some caution is required due to invisible block of collision which can void Lara when she's standing at the place it appears

**Comment by rr-** [comment]
Let's track this particular bit in a new ticket.
