### ISSUE TITLE
T1M bug: walk turning not working with the TR3 sidestep feature

### ISSUE THREAD

**Issue by Trxyebeep** [rr-/Tomb1Main#190]
You can't seem to turn while walking forwards without holding the up key, but only if the TR3 sidestep feature is enabled.

TR2Main implementation of the feature: 
https://github.com/Arsunt/TR2Main/commit/32acf1ccccb68df2cf001416a5fde0edceb18e65

And as said on Discord, to fix: it would better to remove all T1MConfig.enable_tr3_sidesteps occurrences from lara.c, there must be one single check. In input code.

**Comment by thatguyfrombb** [comment]
@Trxyebeep Since we're referencing TR2Main here, have you tested if that's possible at all there? I haven't been able to do it there either (with the sidestep reg added), but I could be misunderstanding your issue.

**Comment by rr-** [comment]
Basically with the previous approach we weren't able to walk forward and turn, e.g. shift+up+left = Lara wouldn't turn.

**Comment by Trxyebeep** [comment]
@thatguyfrombb Yes, it works correctly in TR2Main. the problem here is not being able to turn in the walking animation, without having the forwards button pressed
