### ISSUE TITLE
OG bug: alligators can get stuck in an attack animation and deal no damage

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#194]
Alligators can get stuck in their animation of attacking Lara. They look like they are attacking but deal no damage. If Lara moves, they will move and fix themselves. I think this is an OG bug, but I haven't confirmed it yet to add the label.

https://streamable.com/ld1l6d

May be related to #44.

**Comment by rr-** [comment]
I like the third approach where he bits and doesn't let go, but the crocodile… is flashing as if he was taking damage in a Mario game? :D 

The first approach is good too. Thanks for going the extra mile to record these videos.

**Comment by walkawayy** [comment]
Np. I think the flashing might have to do with the new renderer? In the original issue post, it doesn't flash. Seems like the animation moves the croc up enough that the game thinks it's out of the water for a frame or two.

**Comment by walkawayy** [comment]
WadTool calls the animal Crocodile (on land) and Crocodile (in water). How was the alligator name chosen? Just wondering if it's worth possibly renaming to like Land_Crocodile and Water_Crocodile or something.

**Comment by rr-** [comment]
That's what Core Design chose to call it. I don't think it's an issue

**Comment by Richard-L** [comment]
I honestly would not change this as the solutions seem too fiddly and introduce new undesirable behaviour, like the first bite being missed, or the second bite coming too late. Yes it's a bit odd when they alligtors get stuck and don't do further damage, but people aren't going to float on water waiting for this to happen.

**Comment by walkawayy** [comment]
The first bite can miss in the vanilla game too. And the fix would be optional in the JSON though I'm not sure why you'd want broken AI. Option 1 is still on the table I guess where the alligator does one bite then swims away and comes back around. But it makes the alligators much less aggressive.

Maybe I need to look into how they act in TR4.

**Comment by rr-** [comment]
Hmm @Richard-L can you show an example when this would be an issue? @walkawayy 's solution seemed to be quite resilient on his video. Or have you tested it and confirmed that it's not really as consistent as we'd like it to?

**Comment by walkawayy** [comment]
> 

I can't record video in the compatibility mode, but the crocs are "fixed" in TR4.. They deal damage in the bite animation then do the roll animation like in TR1. But, now they will go back to the bite + roll animations properly instead of only rolling and dealing no damage. However, the bite animation still has that forward movement, so if Lara doesn't move, it will eventually move too far forward through Lara after a bite and will have to swim away and turn to try and attack again. So based on this, maybe we should just go for the option 1 fix in the issue, where it does one bite then swims away to try and attack again. They also possibly added a bigger touch_bits range in TR4 because it can get in a third attack in a row rarely. Though the croc's body is embedded in Lara and the mouth is way too far forward to look like it should attack again.

**Comment by rr-** [comment]
I'd say frame hacks and content injection are too much for this issue.

I still am not sure why solution 3 is not practical – can the croc still get stuck?
Also can the croc grab and not let go of Lara in normal OG?

**Comment by walkawayy** [comment]
> I'd say frame hacks and content injection are too much for this issue.
> 
> I still am not sure why solution 3 is not practical – can the croc still get stuck? Also can the croc grab and not let go of Lara in normal OG?

Ok I'll try to do a full overview. For reference, the croc and alligator were combined together in TR4, so I kind of throw the name around interchangeably.

The in water alligator has 4 animations (also true for TR4 except it has additional animations to transition from land->water and water->land):
0. Swim
1. Bite (slight forward movement+damage)
2. Attack (in place "roll" with no damage)
3. Attack to Swim (slight forward movement)
4. Death

In TR1 when Lara sits still in the water, the alligator swims to Lara, bites, and gets stuck looping animation 2. And since the damage frame is in animation 1, it deals no damage.

The fix I currently implemented moves the damage frame from animation 1 to 2. That way, when the alligator continuously does it's in animation 2 in place, it deals damage because it looks like it has Lara gripped. We don't know the devs original intention since it's not properly implemented. Here's the WAD Tool screenshot showing that animation 2's next animation is 2 hence why it gets stuck.
![tr1-croc-anim](https://user-images.githubusercontent.com/81546780/145855514-bdace423-7fbc-4e85-95e5-6d9f3bf404f4.png)

After looking at the behavior in TR4 however, it seems the devs fixed the bug by making animation 2 connect to animation 3. This works because the croc will go back to the swim animation and can bite again. Here's the WAD Tool screenshot of the TR4 croc showing that animation 2's next animation is changed to 3 (the animation numbers are different because the water and land croc are combined into one enemy type since it can transition between land and water).
![tr4-crco-anim](https://user-images.githubusercontent.com/81546780/145856306-23dfdc09-e392-4d83-85ef-e062ef803dbb.png)
 
In both TR1 and TR4, animations 1 and 3 have some slight forward movement to them. So, if Lara stays still, the Croc eventually will move forward through her body enough to no longer be able to attack.

Relating this back to my [proposed solutions](https://github.com/rr-/Tomb1Main/issues/194#issuecomment-988917559):
In solution 1, the croc does one full attack animation then continues to swim. Damage is dealt in animation 1 like the OG game and TR4. This is more similar to the TR4 behavior, however, there is no potential to perform multiple bites in a row.

In solution 3, the croc deals damage in animation 2. Because that animation loops in TR1, the croc stays in place and can continuously attack if Lara stays still.

**Comment by Richard-L** [comment]
I'm in favour of suggestion No1.

Currently this is what happens:

https://user-images.githubusercontent.com/4934209/145891046-d1cf86ec-244a-4612-a38b-ceac217a3e7d.mp4

Apparently the first bite missing can happen in vanilla too? If we only look at what happens after, I think the damage suddenly occuring much later in the animation than what you're generally used to feels unnatural. Also the croc being stuck and taking damage without opening its mouth anymore also looks a bit odd to me.

**Comment by rr-** [comment]
>Apparently the first bite missing can happen in vanilla too? 

This croc is not the smartest, is it? :D 

Thank you @walkawayy for the detailed analysis. Yeah, in this case I think we should go with solution 1.

**Comment by walkawayy** [comment]
Ok I have (hopefully) the last thing to discuss on this topic.

The OG code checks `if (item->frame_number == g_Anims[item->anim_number].frame_base)` to put the alligator in the `required_anim_state` to perform an attack. The issue with the `frame_base` check is, the alligator only has two useful `current_anim_state`'s, `ALLIGATOR_SWIM` and `ALLIGATOR_ATTACK`. Animations 1, 2, and 3 are all attack states, so multiple damage instances can occur because the alligator can hit its `frame_base` animation number multiple times.

My proposed change would be to change `if (item->frame_number == g_Anims[item->anim_number].frame_base)` to `if (item->frame_number == ALLIGATOR_BITE_AF)` which is like frame 43. This way the damage only occurs once during the animation 1 bite and not during other animations' base frames.

**Comment by rr-** [comment]
I'm fine with such approach. We have to hardcode such frames anyway in other places, e.g. shotgun anims. And I'm pretty sure 60 FPS can handle this.
