### ISSUE TITLE
OG bug: strange pickup radius

### ISSUE THREAD

**Issue by oziphantom** [rr-/Tomb1Main#195]
from pickup.c

```
int16_t PickUpBounds[12] = {
    -256, +256, -100, +100, -256, +100, -10 * PHD_DEGREE, +10 * PHD_DEGREE,
    0,    0,    0,    0,
};

int16_t PickUpBoundsUW[12] = {
    -512,
    +512,
    -512,
    +512,
    -512,
    +512,
    -45 * PHD_DEGREE,
    +45 * PHD_DEGREE,
    -45 * PHD_DEGREE,
    +45 * PHD_DEGREE,
    -45 * PHD_DEGREE,
    +45 * PHD_DEGREE,
};
```
in the first one, the +100 after the -256, is that correct? Does kinda of explain why it hard to pick one up sometimes until you move elsewhere.

**Comment by walkawayy** [comment]
TR5 used the bounds
OBJECT_COLLISION_BOUNDS PickUpBounds = { -256, 256, -200, 200, -256, 256, ANGLE(-10), ANGLE(10), 0, 0, 0, 0 };

Seems like an OG bug.

**Comment by rr-** [comment]
![20211108_094720_axe](https://user-images.githubusercontent.com/1045476/140711280-edeb4110-85cd-4e1f-9592-f3f23554ba8a.png)
OG bug.
