### ISSUE TITLE
Feature discussion: "Current Position" and save crystals

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#198]
Couldn't quite bring myself to call this a "request" just yet. If it becomes one, feel free to rename.

On both console versions you can load a "Current Position" state corresponding to the previous save crystal you saved at.

https://user-images.githubusercontent.com/4934209/140832029-2e8319a8-6328-4cff-a68d-b93b41ddeaca.mp4

PC style saving renders this obsolete, however many people have considerable "save crystal nostalgia". Is it worth adding a pure PS1 saving style for this reason alone, or just to legitimise having the crystals again in the first place?

I find a decent pro argument is that it controls save clutter.

It also increases the game's difficulty of course, whether that's a good thing or not.

**Comment by rr-** [comment]
We already have savegame crystals implemented. They need to be enabled in the gameflow by hand. Using them triggers regular save dialog. The crystals are only consumed if the user does save – if they abort, the crystal can be used again.
