### ISSUE TITLE
Camera bug in v1.3?

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#199]
I've just updated to the new release and notice the camera not adjusting well after climbing up somewhere:

https://user-images.githubusercontent.com/4934209/140834449-d82650a3-f947-4ec7-8364-e38967af8527.mp4

You can fix it by hitting the look button.

Is this a bug or bad setting I have somewhere?

EDIT: seems to have to do with the new free camera feature. The mapping for this would ideally be checked against perhaps or else it's all too easy to run into this.

**Comment by rr-** [comment]
>The mapping for this would ideally be checked against perhaps

I don't understand what you're saying here.

**Comment by Richard-L** [comment]
This isn't a bug, just a matter of unclear key mapping conflict.
