### ISSUE TITLE
T1M bug: Thors Lightning stack corruption

### ISSUE THREAD

**Issue by oziphantom** [rr-/Tomb1Main#205]
![image](https://user-images.githubusercontent.com/7146763/140960209-91422c4a-d966-47b4-bfac-c1955fc09831.png)

Unhandled exception at 0x00F471DA (Tomb1Main.dll) in tombati.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.

in hwr.c:HWR_RenderLightningSegment

**Comment by rr-** [comment]
Does it happen with OG?

**Comment by oziphantom** [comment]
impossible for me to say sadly, as I can't attach a debugger with stack corruption detection to it.
However  I'm pretty sure I have played the Thor room with the vs debugger before and nothing happened.
