### ISSUE TITLE
Feature request: Add additional data to saved games

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#212]
Arsunt suggested saved games could store additional information using the ASN.1 interface description language. X.690 is an ITU-T standard that could be used with BER TLV (Basic Encoding Rules type–length–value) format.

The format would allow additional data to be added to saved games without breaking vanilla TR1 saves, old Tomb1Main saves, or even future Tomb1Main saves with new parameters. The added data could include the current music track, current music track time in seconds, and all previous level info including starting HP, items, statistics, etc.

Necessary additional data:
- [ ] Level completion HP (required to resolve #48)

Desired additional data:
- [ ] TBD

**Comment by rr-** [comment]
The most challenging parts will be
- getting the completed level structure right, so that it's extensible
- getting it to work with the existing savegameinfo
The rest should be relatively simple.
