### ISSUE TITLE
Feature request: support both TR1 and TRUB main menu backdrop

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#215]
Perhaps a nice JSON addition would be to allow choice for which `TITLEH.PCX` to use, TR1's or TRUB's:

![image](https://user-images.githubusercontent.com/4934209/141206948-e03f1184-9137-4404-a18f-4cdb4def48fd.png)

However if later the games are intended to be combined, perhaps always TR1's shows, or depending on the level the user exits from, it updates the backdrop.

I would suggest TR1M creates the respective asset folders, so two PCX files of the same name can coexist.

**Comment by rr-** [comment]
Afaik it needs shipping of a separate title.phd and can be done without code changes.

**Comment by Richard-L** [comment]
The picture is just a copy paste. The actual supply should come from people who actually own the game.

**Comment by oziphantom** [comment]
No the title picture is hardcoded in the exe 
```
case GF_EXIT_TO_TITLE:
            T_InitPrint();
            TempVideoAdjust(2);
            S_DisplayPicture("data\\titleh");
```
I do have some code that will detect a "gold" version and enable it to load another image, needs to handle the fail case. 
The next issue you run into is you can't HD replace the UB image as the hash for the title pic is hard-coded into the tombati and it won't look up the image normally as it is not a texture. TRFan94 made an issue about it.

**Comment by Richard-L** [comment]
Personally don't have a big problem using the stock PCX files for now and forego any upscales.

Upscales will happen every other year by the aspirational user, whenever an algorithm receives a GUI (or similar).

**Comment by annlyt** [comment]
Wouldn't it be easier to have a file for TR1 called TITLEH.PNG and a file for gold called TITLEUB.PCX?

Then code it to detect the -gold shortcut argument and change the background accordingly?

**Comment by annlyt** [comment]
But yes, you can't HD the UB background so something needs to be worked out.

**Comment by annlyt** [comment]
Is there anyway to increase the image dimensions and colour format for PCX?

**Comment by annlyt** [comment]
Because you can get it to load PNG if the quality matches the PCX colours (indexed) Dimensions (640x480) and print size (can't remember but it's very specific).

I managed to get the game to read png files.

**Comment by rr-** [comment]
We'll handle the implementation details. For now it's a non-goal (see milestones and the decompilation progress section in the README).

**Comment by walkawayy** [comment]
I think this was done in 63cbc4401a5e21664b8d94d027899ccec5ecafd7 and can be closed.

**Comment by rr-** [comment]
True. Thanks.
