### ISSUE TITLE
OG bug: Lava particles not working on load in UB

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#226]
If you complete Temple of the Cat in TRUB and enter Atlantean Stronghold, the lava particles will show:

![image](https://user-images.githubusercontent.com/4934209/141693485-87171cde-51a9-4196-8dde-d42b5c11f218.png)

Save and load the game, and they're gone:

![image](https://user-images.githubusercontent.com/4934209/141693493-7ddfee1a-ae7c-4724-894d-bdd29c392c30.png)

The base game doesn't have this issue. Here's a savestate from Natla's mines loaded:

![image](https://user-images.githubusercontent.com/4934209/141693523-d3f007e6-2096-4fc1-b011-edd56dd9febe.png)

TombATI has the very same problem.

**Comment by rr-** [comment]
Fixing this will require something akin to #276.

**Comment by rr-** [comment]
Closing in favor of #418
