### ISSUE TITLE
OG Bug: Lara torsos on Atlantean eggs in UB's "The Hive"

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#250]
Near the end of the fourth UB level "The Hive", the empty Atlantean eggs show these Lara torso objects: 

![image](https://user-images.githubusercontent.com/4934209/142786688-b32e5dfb-9c43-47d7-9856-2e69766782cb.png)

I know this has been brought up before elsewhere, but I don't recall fully why this happens. I believe it may be an OG bug?

Save state if you wanted: [saveuba.zip](https://github.com/rr-/Tomb1Main/files/7577560/saveuba.zip)

**Comment by oziphantom** [comment]
I believe they go over the objects limits which causes issues, but I also though rr upped the limit on T1M..

**Comment by rr-** [comment]
We have more capacity for ITEM_INFO / Items, yes. I'll investigate it later

**Comment by walkawayy** [comment]
WadTool shows the "mutant spawn object" is Lara's torso. I'd guess normally these are hidden by the eggs, and are supposed to disappear when the egg hatches and the mutant appears so the player never sees it. Must not be going away for some reason.

**Comment by rr-** [comment]
Can someone confirm if it's an OG bug or not and if it is, how to reproduce it (apart from loading a broken save)?

**Comment by Richard-L** [comment]
You can see the torso object here: https://youtu.be/hos-BgFkTpI?t=11633

I'm slightly confused by the size of the health bar in this video though. Perhaps TombATI in very low resolution, which makes it appear so big.

**Comment by walkawayy** [comment]
> Can someone confirm if it's an OG bug or not and if it is, how to reproduce it (apart from loading a broken save)?

Ok I just played a fresh game on TombATI and got the bug just be playing normally. After the first few eggs in this room, no more mutants spawned. Upon a save and reload the torsos disappeared.

![AnyConv com__screenshot0000](https://user-images.githubusercontent.com/81546780/148300452-b12e9397-9063-4a43-9837-2506fc8cb8c7.jpg)

**Comment by Richard-L** [comment]
Actually, I always assumed no mutants are supposed to spawn, to symbol "bad" hatchings in the natla-does-experiments sense. But perhaps that's wrong?

**Comment by walkawayy** [comment]
I think the mystery is solved. There's a bunch of pods with flags that are supposed to spawn the abortion mutant (object_number: 34), but the abortion isn't added to the level file. So, nothing spawns. I wonder if there was supposed to be a final boss at the end, but having like 15 in the level doesn't seem right.
```
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 8)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 8)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 8)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 8)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 22)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 22)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 22)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 22)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 9)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 10)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 10)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 10)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 10)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 10)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 34)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 13)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 29)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 29)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 23)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 39)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 39)
../src/game/ai/pod.c 64 InitialisePod bug->object_number: 20)
../src/game/ai/pod.c 66 InitialisePod bug->room_number: 39)
```

**Comment by Richard-L** [comment]
Oh interesting! Sadly Ash has put the stream with the UB level designers on "subscription only" on his twitch but perhaps he can grant us access to find any clues towards the end.

**Comment by walkawayy** [comment]
I tried tinkering with `InitialisePod` and `PodControl` to try and change the spawned mutant to the default mutant (winged flyer) if the game tries to spawn a mutant not in the level file. It seems to work, but I broke save games in the process. :/

**Comment by rr-** [comment]
I'm afraid that without #277 there's no working around this, at least with this approach.

Another approach I can think of would be to disable drawing Lara's butt where it doesn't belong.

**Comment by walkawayy** [comment]
Shoutout to Ash for reaching out to the original devs. Here's their response:
```
"Yeah, I like to say they were trying to grow more Laras:) it was a bug we noticed but left it in, something to do with wanting the eggs to hatch anyway…"
```

So it seems like the goal was to have some empty egg hatches like the Atlantis level.
