### ISSUE TITLE
T1M bug: brightness setting not getting saved

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#251]
The ingame brightness value always resets to 1.0 when I quit the game then return to it.  Can the brightness value be saved in a future release?

**Comment by rr-** [comment]
Yes, sorry about that.

**Comment by atombraiderfan** [comment]
No problem, thank you for answering.

**Comment by rr-** [comment]
Will be fixed in the next release (1.5.0).
