### ISSUE TITLE
OG bug: Scion doesn't stop making the room go Boom Boom

### ISSUE THREAD

**Issue by oziphantom** [rr-/Tomb1Main#252]
In "The Great Pyramid" blow up the Scion then stick around, run around the room 4/5 times or so.. then leave the room. 

Yeah it doesn't stop. Scion3Control is still active and the static internal counter is now over the FRAMES_PER_SECOND * 3 mark so it just keeps going and going and going. 

Not sure if this is our bug or OG though.

**Comment by rr-** [comment]
I just debugged it and the `counter` for Scion3Control correctly stops at the value 90 and removes itself from active items. The earthquake that keeps going on is dev intended as the entire pyramid is collapsing. The earthquake is caused by `TestTriggers` that spawns an `O_EARTHQUAKE` effect. All of this is consistent with OG.

**Comment by oziphantom** [comment]
No. 
Normally you play the level with the small odd 50 scale shake. 
The Scion blows up with a -200 scale shake. 
The bug above causes the whole level to continue with the -200 shake making it unplayable. 
Here is a video showing the difference https://youtu.be/DXmnbiQqrnc

**Comment by rr-** [comment]
Next time please mention crucial information such as "save and reload for this to happen"

**Comment by oziphantom** [comment]
well I'm not Rap_Wins I can't finish the game NL, however I just started a new game, used X to skip, kill abomination, flew around the level to get back to the scion via the normal path so it was active, shot it, did the run around the room a couple of time, then left the room and the issue still happens. So "save and reload" is not needed.
