### ISSUE TITLE
Feature request: Screenshots Storage Place and Naming

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#255]
I'm proposing to move the screenshots (made by pressing _Print Screen_ button) into 'screenshots' folder (already implemented in TR2Main project), also we can use naming that indicates which game is used. Maybe also use level name, for example:
• screenshotTR10001.jpg
• screenshotUB0001.jpg
(without level name but with game name added) OR:
• TR1-LEVEL1-0001.jpg
• UB-CAT-0001.jpg
 (with game name AND level name - can be useful to distinguish screenshots between TR1, UB and future Tomb1Main-based community levels).
 
 Visual Example:
![Снимок (2)](https://user-images.githubusercontent.com/25227941/145109520-74ee5736-3d5b-4bdf-90dc-d0d73784f609.png)

![Снимок (1)](https://user-images.githubusercontent.com/25227941/145108903-e07a9eed-e19a-40e6-8d36-33ede093e817.png)

If that is going to be implemented, we can have forever 'clean' look of the game root folder

**Comment by walkawayy** [comment]
No where do we have access to game names such as Tomb Raider, Unfinished Business, or a potential custom game name. So I implemented screenshots named by level which I think should be ok? @Defrago what do you think.

![image](https://user-images.githubusercontent.com/81546780/148281957-83f2832f-0d24-4b74-804c-9b7432683fa8.png)

**Comment by rr-** [comment]
LGTM. We could get the game name from the gameflow file name but I don't think it's a good approach. Adding the game name to the gameflow would be better, but there's no guarantee that level builders will pay attention to this new field, given how it will have relatively low impact.

**Comment by rr-** [comment]
Actually, on second thought, can we have names that include timestamps?

```
20220105_172623_Atlantis.jpg
```

This is what I've been using for years for desktop screenshots (without the level names ofc). Pros of such naming:
- It works well with sorting
- This order is actually an [international standard](https://en.wikipedia.org/wiki/ISO_8601)
- I can look back at my files and think 'wow I played TR1 on Christmas, way to go, me'

Dupes (screenshots made within the same second) could be resolved in a number of ways:

- `20220105_172623_RNG_Atlantis.jpg` (where RNG are random alphanumeric characters)
- `20220105_172623_Atlantis_(2).jpg`
- `20220105_172623_123_Atlantis.jpg` (where 123 is milliseconds)

**Comment by walkawayy** [comment]
Not a bad idea. I name stuff like this for work sometimes and the only downside is UTC time is not that human readable (and idk if many time libraries exist in C). The date is nice though. I’ll add that when I address your other comments.

**Comment by Richard-L** [comment]
I would do yymmdd-hhmmss, and just add a 2, 3, n at the end if someone were to actually hold down the PRINT key

**Comment by walkawayy** [comment]
How does this look? It only adds the extra `0000`, `0001`, etc if you rapidly press print screen during the same second.

![image](https://user-images.githubusercontent.com/81546780/148328873-04f6e53b-f70d-4ae9-9125-17746c7ffdf0.png)

**Comment by rr-** [comment]
Looks good, but I don't think we need to use `000` prefix now for the duplicates, plus I'd start with `2` like @Richard-L suggested.

**Comment by Richard-L** [comment]
Looks great @walkawayy . I wonder how many screens would be physically possible to take within one second. If the hardware is fast enough, could it exceed 99?

**Comment by rr-** [comment]
AFAIK we're hard capped at 30 FPS.

**Comment by Richard-L** [comment]
Oh and that includes screenshots? Had assumed it would take duplicates of the same frame if it's fast enough

**Comment by rr-** [comment]
We process keyboard state / inputs on every frame and wait for a new frame inbetween. It's quite oldschool, but any changes to this flow would be dramatic in terms of size and scope.

**Comment by Richard-L** [comment]
Sounds good though. The only case then I guess where a double digit could be broken was a 120fps branch? ;)

Out of curiosity, if no numbering was given to screenshots, what would the code do? Would it simply overwrite the same file until a second has passed? I'm almost thinking that would be fine, also to keep the code simpler.
