### ISSUE TITLE
OG bug: Lara fails to grab some bridge edges and runs into bridge invisible walls

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#256]
Lara fails to grab / pull up on certain parts of some ledges while other parts of the ledge work fine. Can be easily seen on the Caves 2 bridge. Not sure if this affects more than just bridges.

Lara fails to jump and grab a specific part of the bridge.
https://streamable.com/krh50h

Lara can't hop back and grab the ledge at this part either.
https://streamable.com/q1zntw

**Comment by oziphantom** [comment]
it would be interesting to repeat the test on the 60fps branch, as I had a bunch of "can't grab ledges" bugs that I had to add a hack to fix. Interesting if it fixes these parts as well.

**Comment by stohrendorf** [comment]
Problem with that bridge is described here: https://www.tombraiderforums.com/showpost.php?p=8333333&postcount=34 - basically all you need to do is to check if Lara is in the same sector as the bridge before patching the floor/ceiling heights.

**Comment by walkawayy** [comment]
Cool thanks. I started porting some of the Edison fixes yesterday, but it didn't seem to fix it. I'll look at again later tonight.

**Comment by walkawayy** [comment]
Thanks for the assist @stohrendorf. I think I have it working based on your Edison Engine fix. Here's a video showing some different jumps and grabs.

https://streamable.com/q6zamg
