### ISSUE TITLE
Feature request: D-pad navigation in the menus

### ISSUE THREAD

**Issue by grogfella** [rr-/Tomb1Main#268]
While the existing X-input controls are a godsend for those of us with a gamepad, I personally much prefer using the D-pad to navigate menus over analog stick clicks. Could it be possible to change the controller implementation to make it possible to use either the D-pad or the analog stick to navigate the menus?

**Comment by oziphantom** [comment]
are you using the "enable_xbox_one_controller" option?

**Comment by rr-** [comment]
Currently it is not possible to override any of controller settings. All controller issues shall be tackled in #279.
