### ISSUE TITLE
Feature request: insert the braid mesh in every level

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#27]
Related to #8. Currently, the hair mesh is only available in the Lost Valley level. Requires input from @Arsunt on how to structure the softpatch JSON structure for levels.

**Comment by annlyt** [comment]
https://github.com/skalogryz/larasbraid 

This tool injects the mesh into the level files. Might be worth looking into. I've used it personally. 

![tombati60FPS 2021-10-03 13-28-29 original](https://user-images.githubusercontent.com/13076939/192096262-4b1f6ab8-8ec5-4076-8d03-c3caf230b4c7.jpg)

Ignore the 1995 TR1 prototype head mesh, that is another thing entirely (tho if it could be injected as an option that would be amazing). The braid can be injected and it does not mess textures up at all as the braid uses a single palette colour.

**Comment by rr-** [comment]
Thanks, this is a great find.

Notes for whoever's brave enough to take this – for now I'm OK with hardcoding this somewhere in the level loading routines. In the future however, it'd be great to offload this and similar fixes (pyramid secret # fix comes to mind) to LUA or something. As such I think the best course of action is to create a new gameflow sequence that allows injection of new objects/meshes from external files, and bundle the braid file as part of our binary blobs shipped with T1M. That way the routine can be reused in the future with greater ease than if we were to hardcode the brain mesh data in the .exe, however even this would be a welcome addition.
