### ISSUE TITLE
T1M bug: default brightness is too high

### ISSUE THREAD

**Issue by nfraihat** [rr-/Tomb1Main#270]
The default brightness value of 1.0 is too high compared to the original/tombati, leading to an overexposed look to some areas.
A value of 0.8 matches the original. Comparison attached
![tombati](https://user-images.githubusercontent.com/49598539/146070616-d5517b0a-04f4-4cc7-969d-bee962808426.jpg)

![t1m](https://user-images.githubusercontent.com/49598539/146070564-5a195999-b6b7-40a2-b205-f238b9075bff.jpg)

**Comment by rr-** [comment]
Are you sure about this? This is how original TombATI looks for me.

![20211214_230741_yvg](https://user-images.githubusercontent.com/1045476/146087070-e00accb3-12a7-4a26-85cf-e012665d5676.png)

**Comment by nfraihat** [comment]
My apologies. I must have lowered the brightness years ago for tombati in comparison with the dosbox version and forgot about it (my config file was last modified Jul 2017). This can be closed.

FWIW Here's a screenshot from the dosbox version, even my config looks a bit bright. 
![Screenshot (114)](https://user-images.githubusercontent.com/49598539/146090614-0d8359f7-e4ff-4f57-b2b2-e9b8737ffe6f.png)

**Comment by rr-** [comment]
No worries, the important bit is that we solved it. Thanks!
