### ISSUE TITLE
OG bug: Black flicker when switching between rings in inventory.

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#272]
Hi, hope I'm not spamming here too much but I've thought to ask if the black flicker in the inventory can be removed.  Basically when you press up/down while in Lara's inventory, there's a moment of a black screen for a split second before reaching the other ring.

**Comment by walkawayy** [comment]
Ya we have an issue for it #75. I tried looking at it, and messing with the camera pitch sometimes helped and sometimes didn't. But it also messed with how the items in the ring behaved. So I'm not sure how to fix it yet. Gonna close this as a duplicate.
