### ISSUE TITLE
Bug: at 320x200 resolution the details screen is scaled improperly

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#275]
This is super low priority, and I don't know if anyone even plays at a resolution this low, but the details screen is improperly scaled at the lowest resolution of 320x300. I noticed while checking the load/save game slot fix. I checked TombATI to see if it happens there, but they only have perspective and bilinear options in game.

![image](https://user-images.githubusercontent.com/81546780/146429489-1b78a484-c23d-46ff-bb3d-27154440e0e9.png)

**Comment by rr-** [comment]
Honestly IDK what to do with this.
Also is there anybody in the world who plays at 320x200? To me it seems that this resolution exist only to make our lives miserable with bugs such as this one.

**Comment by walkawayy** [comment]
Is there any legit reason to even have this resolution? Can we just remove support for it? 480p minimum is more than enough IMO.

**Comment by rr-** [comment]
The only legit reason is that it is also available in TombATI. IMO it's OK to remove it. Pinging @Richard-L for his viewpoint as well.

**Comment by Richard-L** [comment]
Definitely remove this ancient resolution in my opinion
