### ISSUE TITLE
Feature request: new savegame format

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#277]
I'd like us to design a new savegame format that can easily maintain backwards compatibility in case we need to make changes to what gets saved (see #226, #261, and possibly more).

Arsunt's proposition was to use [TLV](https://en.wikipedia.org/wiki/Type%E2%80%93length%E2%80%93value) and I think it is sensible, however I think that it's OK for us not to maintain backwards compatibility with TombATI.

I would also like to suggest [BSON](https://bsonspec.org/spec.html).

I'd still like to support legacy format, but only loading.

**Comment by rr-** [comment]
Pinging @walkawayy and @oziphantom for opinion on using BSON and @richard-l and @defrago on opinion on legacy compatibility.

**Comment by Richard-L** [comment]
Always a tough one. Usually it's fair to sacrifice legacy compatibility in favour of technical advancements, but I must say it has been very enjoyable that old savestates were perfectly readable by TR1M, and stayed so between all the recent releases. I also noticed the guy with the Atlantis issue mention save games from site's like Stella's, which I suppose couldn't be used with a new save format.

How much work would a legacy savestate converter be do you think that runs under the hood? Just thinking if something like that could allow the best of both.

**Comment by rr-** [comment]
I'm OK with keeping compatibility with loading old TombATI saves. The cost isn't too big, we can cram a few hacks if needed. However what I'd like to avoid if possible is the creation of backwards-compatible saves, so if the user saves their game, it would be no longer playable in vanilla TombATI. Would that be a huge bummer?

**Comment by Richard-L** [comment]
Personally don't think that would be a problem.

**Comment by walkawayy** [comment]
I don't think so either. Main problem right now is TombATI -> Tomb1 Main saves.

**Comment by oziphantom** [comment]
bson is fine, doesn't support 16bit ints which might make it a bit of a pain, either doing dummy int32 reads then cast to actual values etc. Or treat them all as byte arrays. The "real trick" will be checking which format the file is in, and if its our BSON or original. Luckily for PS1 compatibility the save file holds the file name in it, which isn't actually the file name it's the "description". Thus they have a fixed number of options, until one gets to custom levels. But one can probably safely assume that all names will be Extended ASCII letters only, numbers and punctuation only. Which gives us the ability to make a key. When can then have versioning, also as this is a DOS name the filename if that is what is saved on PC version should be at max 8.3.

The way to not go mad with supporting changes and expanding formats is to make a "constructor" that will init all values of the load before, then load data into it, thus anything missing in the format gets the best default value it can and you don't have to have keep a hundred loaders around, however for it to work every data field must be given a name and parsed 1 by 1 which is also tiring, especially when one doesn't have objects. 

a common trick to keep file size down, parsing speed up is to make 4byte TAGS such as 'T','i','m','e' for the timer, 'C','L','v','l' thus you can switch on a 32bit byte,(See the IFF format for example) I guess these days we could go for an 8 byte tag and switch on a 64 bit. 

If "we need to make files that can go back to original/TombATI that file format is fixed and making a command line tool that pulls out the required fields from our new format and spits out a "original" format shouldn't be too hard and only needs to be done once.

**Comment by rr-** [comment]
I'll also add gzip compression cause BSON will cause add lots of duplicate keys. Uncompressed data can go up to 100k from my very pessimistic calculations, but gzip should shred it.

**Comment by rr-** [comment]
Some simulations of the compressed data:

```python3
from random import randint
import bson
import zlib

payload = {
    "levels": [
        {f"levelfield{j}": randint(0, 10000) for j in range(20)}
        for i in range(10)
    ],
    "extra": {f"extrafield{j}": randint(0, 10000) for j in range(100)},
    "items": [
        {f"itemfield{j}": randint(0, 10000) for j in range(20)}
        for i in range(200)
    ],
}
print(len(zlib.compress(bson.dumps(payload))))
```

> 15929

I believe this should be even lower for real world scenario.

Coincidentally compressing a normal JSON yields only 1 KB worse results.
