### ISSUE TITLE
Feature request: Controller support

### ISSUE THREAD

**Issue by ErickASJ1977** [rr-/Tomb1Main#278]
Greetings.
Would it be possible to update the xinput control configuration?
TR3 sidesteps are only available with keyboard.
If I use any xinput controller, left sidesteps with the left trigger does not work.
And the rest of the buttons are set as in The Angel of Darkness, not  as in the original PSX version.

**Comment by rr-** [comment]
Hey, currently it is not possible. This is similar to #268 and will be tackled in #279.

**Comment by rr-** [comment]
https://wiki.libsdl.org/CategoryGameController
