### ISSUE TITLE
OG bug: black lines on texture edges

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#283]
People have been reporting black lines on the edges of textures. Here is a video to show this behavior. Look at the edge in the corner in front of Lara as she moves and you can see a black line flickers. Probably not an easy one to solve.

https://streamable.com/alh01k

**Comment by atombraiderfan** [comment]
Also the manor foyer is a good place to get a view of these black jagged lines.

![screenshot0001](https://user-images.githubusercontent.com/94776985/147047955-fd7069de-0c06-4c9b-9db3-4520ffa96ece.jpg)
,

**Comment by oziphantom** [comment]
This could be 1 of two things.
a.) the texel coords are not aligned properly and we are getting artifacts from the texture UVS. As each texture was its own page and each polygon is 0,0 to 1,1 that would be a bit odd, adjusting the u,v to be middle of the texel so 1.0/texture_width/2.0,1.0/texture_width/2.0) and then (1.0-1.0/texture_width/2.0, 1.0-1.0/texture_width/2.0). Also making sure the texture wrap setting is set to a "CAMP" mode would help.  But I would only expect this to be a case with HD textures which seem to be packed. 

b.) welcome to fixed point maths and at 640x480 it is in tolerance but once you get above you are out of tolerance and the positions of each vertex are slightly off when converted to floating point in the engine and we are getting errors as the points are not "snapped" to each other and thus the lines don't follow each other 100%. You see this is the original its the "wobble". Not that much you can do as each quad is drawn individually, adding them to a vertex index buffer and doing "near" checks to find the right actual vert to ensure they get the exact same value is probably the best that can be done in this engine. 

A quick way to check if its A or B would be to change the fill colour of the clear buffer command, and if the black remains black then its a.) and it changes then its b.).

**Comment by rr-** [comment]
![screenshot0010](https://user-images.githubusercontent.com/1045476/147127765-d1deea9a-7dd2-487a-87d1-c5538b49efc4.jpg)

This is with #0000FF clear color.

**Comment by rr-** [comment]
![screenshot0000](https://user-images.githubusercontent.com/1045476/147130577-b0daaee7-355b-4510-8667-6d1ee5c81f74.jpg)
 This is with textures completely disabled.

**Comment by rr-** [comment]
I think certain surfaces are more prone to exhibiting this problem. Here's a screenshot where we round every polygon's position to a 10,10,10 voxel precision.

![screenshot0011](https://user-images.githubusercontent.com/1045476/147136580-4c054266-816e-4e3c-b232-0d6b5994f18e.jpg)

Note the seam caused by the window sill – the engine calculates its position separately from the wall. These two surfaces have only 1 vertex in common.

Anyway I don't think TR2+ exhibits this problem. Maybe @Arsunt knows why this might be happening?

**Comment by rr-** [comment]
Increasing the precision of VBuf calculations  to float seems to fix the issue. VBufs are only used to render things, so I'm not worried about it breaking the AI, animations etc. Created a PR :)
