### ISSUE TITLE
Bug/question: Black polygons

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#284]
I'm getting this on the newest Wine:

![screenshot0005](https://user-images.githubusercontent.com/1045476/147129114-b7de2a71-bb5d-48db-8e72-a5511e4cd2c5.jpg)
![screenshot0010](https://user-images.githubusercontent.com/1045476/147129117-57b0401b-739c-46ff-8521-0c9b68ea3fd5.jpg)
![screenshot0037](https://user-images.githubusercontent.com/1045476/147129118-52597004-e0c1-4a9b-853c-9a5f92639fe5.jpg)

I'm not sure if this is my driver's fault, Wine's fault, or T1M's fault. Can someone confirm on Windows?

**Comment by rr-** [comment]
I don't seem to be getting this on my virtual machine.

**Comment by walkawayy** [comment]
I couldn't reproduce. Maybe using lower resolutions causes this?
![screenshot0000](https://user-images.githubusercontent.com/81546780/147137241-922635b7-d077-4e59-9cbe-01a6657565e4.jpg)

![screenshot0001](https://user-images.githubusercontent.com/81546780/147137258-f87508d5-a318-4bae-9ce4-c16c897fc5b1.jpg)

**Comment by walkawayy** [comment]
And usually if I have a texture issue, it seems to be due to camera clipping. Like this spot in the cowboy room of Natla's Mines. But the texture doesn't go black, just invisible.

![screenshot0002](https://user-images.githubusercontent.com/81546780/147137440-b5e4f2b7-3957-4f9e-97dd-4ef3482de57a.jpg)

**Comment by rr-** [comment]
Merry Christmas :) 
![20211222_194524_jla](https://user-images.githubusercontent.com/1045476/147140510-ebbd54e3-a1dc-426a-8cc7-b722d634eb43.png)
