### ISSUE TITLE
Bug: Jumping onto suit of armour causes Lara to fall into the void

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#299]
Just came aross this bug when playing on version 2.2.1, not sure if this is an OG or T1M bug.

https://user-images.githubusercontent.com/94776985/148386011-a866e60a-2404-48de-9b3c-1a9d1f0c42b9.mp4

**Comment by oziphantom** [comment]
It's in TombATI at least

**Comment by nfraihat** [comment]
It's also in the dos version/steam.

**Comment by walkawayy** [comment]
o.o

![image](https://user-images.githubusercontent.com/81546780/148477623-f4aa2fa5-8312-4212-bc3e-578635ce2ca8.png)
