### ISSUE TITLE
Tomb1Main Bug: Controller Left Trigger

### ISSUE THREAD

**Issue by ALIEN79nator84** [rr-/Tomb1Main#302]
When using a controller the left trigger does nothing. The right trigger sidesteps right like it should, so this issue only relates to the left. I tested this with multiple controllers and the issue still occurs.

**Comment by rr-** [comment]
All controller issues should be handled as part of https://github.com/rr-/Tomb1Main/issues/279.

**Comment by oziphantom** [comment]
I just tested this on my original builds and LT and RT work. However it is broken on 2.0.

**Comment by oziphantom** [comment]
when to code got converted to bit fields rather the bit enums this happened

```
// check Z
        if (state.lZ > 512) {
            linput.step_left = 0;
        } else if (state.lZ < -512) {
            linput.step_right = 1;
        }
```
the `linpujt.step_left` should be set to 1 or true even.
