### ISSUE TITLE
Bug: Underwater effect noise only plays once

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#305]
The underwater ambient effect noise (`SFX_UNDERWATER`) only plays once.

**Comment by rr-** [comment]
I don't understand; could you please describe what sound exactly or post a video of it?

**Comment by rr-** [comment]
Guessing from the PR it's about the water ambience (blubb blubb) sound not playing when the camera is above the water surface. That's desirable IMO.

**Comment by walkawayy** [comment]
Listen to 12:08 on PS1: https://youtu.be/BltNSs9Vzdg?t=728

14:55 on PC: https://youtu.be/lN-5VLPakmI?t=895

The background underwater sound only plays once on PC.

**Comment by rr-** [comment]
Thanks. I'll test it later

**Comment by rr-** [comment]
Is this really an OG bug? I never noticed this, wow.
