### ISSUE TITLE
Pause audio in inventory screen

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#309]
Not sure if this counts as a "feature": Currently music audio tracks keep playing over the inventory. I'm not sure if this is the PC's regular behaviour, but I would like to motivate changing it to pausing music while the inventory is open, and resuming it when the inventory is left. This (coincidentally) is PS1 behaviour, and I think makes more sense, as the music is intended to play along with the player's experiences during specific scenes in the game.

**Comment by walkawayy** [comment]
I can see both sides of this maybe? Audio does pause on the dedicated pause screen:
![image](https://user-images.githubusercontent.com/81546780/148662758-62fc5c51-ba27-46d0-8499-dee4da002bce.png)


But you can see on PS1 in this video that the audio pauses on the inventory screen during the Larson fight:
https://www.youtube.com/watch?v=BltNSs9Vzdg&t=844s


Also I did notice that while music pauses on the pause screen, stuff like the running water noise near the Lost Valley stream don't pause.

**Comment by rr-** [comment]
>Also I did notice that while music and ambient noises pause on the pause screen, stuff like the running water noise near the Lost Valley stream don't pause.

That's definitely a bug.

**Comment by walkawayy** [comment]
As far as inventory music, there are these [two lines of code](https://github.com/rr-/Tomb1Main/blob/5642e9d7564a334af6690c9e2c6a9aa9ad63af74/src/game/inventry.c#L69) suggesting at least the ambient noises should pause while in the inventory screen. But due to where those calls are, they are only called once, so they sometimes cause a weird audio glitch.

**Comment by rr-** [comment]
So to recap – we want the ability to make inventory behave like the pause screen and kill all music, is that right?

**Comment by walkawayy** [comment]
I think so. Here's how it's done in [TR2Main](https://github.com/Arsunt/TR2Main/blob/5bec0d77667276d37eef4e4e23d295a06ae2a596/game/inventory.cpp#L115). Looks like it's similar code to Tomb1. Seems like the audio was supposed to pause during the inventory like PS1 but it is done incorrectly.

**Comment by Richard-L** [comment]
Yup, pause audio in inventory, resume when returning to gameplay
