### ISSUE TITLE
Feature request: read gameflow from an external JSON file

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#31]
TombPC.dat alternative from later games. It's content should override flags that embedded into original TOMB.exe (or TOMBATI.exe at current state). It can also contain values for language options if localizations will become possible.

[Example of values that currently stored and can be edited](https://www.tombraiderforums.com/showthread.php?t=223679)

Current Tomb1Main.json will become too big with all information moved into it. It's better to split some values to several files. If game doesn't detect them or correct values inside, current Core data must be used.

**Comment by rr-** [comment]
This needs good planning

**Comment by rr-** [comment]
Blocked by #55.

**Comment by rr-** [comment]
Done on master
