### ISSUE TITLE
Bad performance with Tomb1Main

### ISSUE THREAD

**Issue by Storm3000** [rr-/Tomb1Main#312]
Hi, I'm having bad performance playing TR1 with Tomb1Main. I have a Ryzen 3 processor with videocard Vega 8 integrated.

Sometimes I've noticed some performance issues in some big areas. For example, the two wood bridges in The Caves level, or the fountain in City of Vilcabamba level. Since I'm using TombATI I have noticed these kind of areas have FPS drops. These areas works fine usually, but sometimes if I load the game I notice this occasional lag randomly. I'm playing at 1920x1080, but it's happening with any resolution.

And now with Tomb1Main it's happening exactly the same. The game only works stable if I disable the Vsync from my videocard settings, but I notice a crackling sound here and there, but is not really annoying because it happens very few times. Is not the best way to play, but oh well...

I'm not the only one who has this performance issues. I found other posts related to this:

https://www.tombraiderforums.com/sho...d.php?t=218894

https://steamcommunity.com/app/22496...8119306812529/

https://www.tombraiderforums.com/sho...d.php?t=226581

It seems is maybe related to the fullscreen_hack option in glrage.ini and definively to the Vsync, but that's strange because you said that Tomb1Main is not using TombATI anymore. Here is a pic with the FPS drop:

![screenshot0000](https://user-images.githubusercontent.com/28787944/148667547-65148ced-04eb-43d6-9629-922c209a1254.jpg)

**Comment by Richard-L** [comment]
Meanwhile I'm having 100% performance on a PC from 2010.

Do you have any specialised driver settings or overlays like Reshade, etc?

**Comment by Storm3000** [comment]
No, I always played with TombATI and I had this problem before. Now I only added the Tomb1Main and the "DATA", "FMV" and "music" folders. Everything works fine, but sometimes with Vsync enabled my game suffers these FPS drops on big areas randomly. This means the game runs perfectly smooth all the time, but sometimes if I skip a level or load a level, the lag will happen. If I disable the Vsync the game works fine, but I can hear a crackling sound in some sound effects, but is not very annoying because it happens from time to time. The only thing I can assume for now is some kind of desynchronization between video and sound.

**Comment by walkawayy** [comment]
The audio crackling fix is pending. I think that happens to most people. But the FPS drops probably shouldn't be happening.

**Comment by rr-** [comment]
Us "not using TombATI" means that T1M no longer needs TombATI to work. It does not change the fact that it is a reverse-engineered reimplementation of TombATI and as such it shares its bugs and woes.

Sadly IDK how to improve performance of those areas. I experience those FPS drops as well on Wine. One way to improve performance is to disable the bilinear filter that could get you 2-3 FPS.

**Comment by Storm3000** [comment]
Is it possible to add the Vsync option in main menu or cfg files?

Is the only way I found to fix the FPS drops and I only can do it setting my videocard options.

**Comment by rr-** [comment]
Thanks for this discovery; sure it is possible :) @walkawayy would you like to implement it? We'd need to expose the `bool vsync = true;` from `GFX_Context_Attach` to the config.

**Comment by Richard-L** [comment]
Is the vsync relating the OP's performance issues? Or should vsync be its own issue?

**Comment by walkawayy** [comment]
> 

I can make it an option ya.

But if it's enabled by default, doesn't that mean it's already being used? So the question is why is the performance bad until they double enable it in the video card settings too?

**Comment by rr-** [comment]
GPU driver settings override what we request via Windows GL (wGL). We can't have "double vsync" :D

**Comment by walkawayy** [comment]
Ya that’s my point. How does enabling it via video card fix performance if it’s already always enabled in its current form?

**Comment by rr-** [comment]
Vsync is known to cause lags. I understood that it is disabling that helps.

**Comment by walkawayy** [comment]
Ok I couldn't tell from their post. We can make it an option and go from there. Should it be added to the sunglasses inventory menu?

**Comment by rr-** [comment]
I don't know. No preference :)

**Comment by rr-** [comment]
@Storm3000 does 2.5 version solve the performance issue for you? Note that you'll need to switch the vsync settings manually.

**Comment by rr-** [comment]
Closing due to lack of response.
