### ISSUE TITLE
T1M bug: End of level darkened screenshot missing

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#324]
The background for the end of level stats screen is black instead of a darkened screenshot.

I'm using T1M version 2.3

![20220114_130221_Caves](https://user-images.githubusercontent.com/94776985/149520151-1a5bb5a4-6c4a-4b6e-952c-d1f44c9016eb.jpg)

**Comment by walkawayy** [comment]
I was looking into fading the inventory and level end screen like the PS1 version, but I don't really understand the rendering code. I'm also unsure if it's possible with the current rendering code.

**Comment by rr-** [comment]
Does anyone know the minimum version of T1M that has this bug?

**Comment by walkawayy** [comment]
No idea. I think since I started developing, it's been black, but I could be wrong. Since at least October/early November maybe?
