### ISSUE TITLE
Feature request: Level Select feature

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#33]
Possibility to select level from predefined list (TR2+ way). Can be enabled via [#31 file](https://github.com/rr-/Tomb1Main/issues/31).

By now it's only possible to have saves at every level or using cheat to skip them.
[SaveATI.zip - contains saves mostly at the start of every level and last Caves level with NG+ enabled](https://github.com/rr-/Tomb1Main/files/6055745/SaveATI.zip)

**Comment by Richard-L** [comment]
Maybe for some materials and ideas:

PS1 Level select, based on what you have unlocked:
![level-select](https://user-images.githubusercontent.com/4934209/137603304-2015448a-1774-4c6c-bd41-d976e51c7dad.png)

XProger has done a nice contemporary rendition of this in OpenLara:
![level-select_openlara](https://user-images.githubusercontent.com/4934209/137603311-26b27821-5e71-4761-b13b-7d83c2e2c6ad.jpg)

If you wanted to take things a bit further, you could combine this with the PS1's "Story so far" feature some later TRs have, that lets you rewatch cutscenes or FMVs. So for a fully unlocked TR1, perhaps something like this:
![level-select _ suggestion](https://user-images.githubusercontent.com/4934209/137603334-77b71b43-a6f7-4aa4-9261-3ec0eab95e46.png)

From there you could add the TRUB levels, and consider an optional reordering of them where its Lv3 and 4 come first to be somewhat more canonical.
