### ISSUE TITLE
OG Bug: Lara's scream repeats when dropping from a high enough place 

### ISSUE THREAD

**Issue by nfraihat** [rr-/Tomb1Main#330]
You can check this at the torso boss fight

**Comment by Rapora9** [comment]
I don't see that as a bug. I think it's a feature (that I like).

**Comment by rr-** [comment]
Same

**Comment by rr-** [comment]
Closing, in case someone voices a strong opinion to remove this behavior, we can revisit it and make it as a configurable setting.
