### ISSUE TITLE
Bug: Up arrows show in ring menu during a save crystal level save

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#337]
In save crystal mode, there are up arrows on the end of level save screen at the top. These normally indicate key items in the ring menu, but should not show in save only mode. This is purely visual as you can't actually move up.

See this screenshot: (other visual glitches have been fixed)

![20220115_161315_Lost_Valley](https://user-images.githubusercontent.com/81546780/149637917-aa7caff8-d390-4482-99d0-2e92083fbeaf.jpg)

**Comment by rr-** [comment]
Actually this also happens when the player presses F5 and Lara has some keys in her inventory.
