### ISSUE TITLE
T1M bugfix: Airbar doesn't appear when it should

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#35]
Airbar doesn't show at all with my settings:
![Снимок (2)](https://user-images.githubusercontent.com/25227941/109404147-630e9780-7974-11eb-8d30-3118bc010f63.PNG)

**Comment by rr-** [comment]
Have you waited till it actually goes below 20%? It really takes ages in TR1.

**Comment by Defrago** [comment]
Yes. It's only appearing in Flashing state (less than 20%), otherwise not shown at all

**Comment by rr-** [comment]
That's the intended behavior when you set it to `flashing`. Try choosing `default`.

**Comment by Defrago** [comment]
Not actually fixed in 0.8.2

**Comment by rr-** [comment]
> Regarding health and airbars, I'm bit confused. I thought "flashing" is the only mode that enabling flashing while amount of it's content is low. It's the way OG handles it (at least DOS and PS ones). I'll stick to default then.

I can see where your confusion comes from. In TombATI it doesn't show when flashing.

**Comment by rr-** [comment]
>Airbar doesn't appear on default as well

Can't reproduce.

**Comment by Defrago** [comment]
Can confirm it works again
