### ISSUE TITLE
Bug: level stats trigger FMV skips too fast

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#359]
Holding the Action key for too long now skips both the level stats screen and FMVs. Regression from #341 .

**Comment by rr-** [comment]
Also @richard-l should we also skip cutscenes (e.g. the one with Larson, not the movies) with the Action key?

**Comment by Richard-L** [comment]
I would tend to agree yes. This would be behaviour unique to TR1M afaik.

Sorry to hear about the regression
