### ISSUE TITLE
Bug: Could not allocate enough memory crash

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#369]
While testing #360, I ran into this error + crash when skipping a level. I wasn't skipping through multiple levels quickly. But I did skip levels through an entire playthrough and start a new game. Someone also reported this issue on TRF. Here's a screenshot of the error and my log.

![image](https://user-images.githubusercontent.com/81546780/150378155-7f51a21a-a047-4054-a4f4-210f57dfea11.png)

[Tomb1Main.log](https://github.com/rr-/Tomb1Main/files/7906824/Tomb1Main.log)

**Comment by rr-** [comment]
We had, but in fd63a956 a bad conflict resolution reintroduced the faulty loop.
