### ISSUE TITLE
OG bug? Mutant mummies not combusting in some levels

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#372]
I've noticed in the following Egyptian  levels that mutant mummies die without explosion sound or fire sprites:

- City of Khamoon
- Return to Egypt
- Temple of the Cat

I'm curious if this is an OG bug or whether there's another explanation.  Mutant mummies do however combust like their Atlantean counterparts in Obelisk of Khamoon, and Sanctuary of the Scion levels.

**Comment by rr-** [comment]
I always thought this was an intended mechanic as a means to scale the game difficulty.

**Comment by Rapora9** [comment]
> I always thought this was an intended mechanic as a means to scale the game difficulty.

That's my thoughts too.

**Comment by atombraiderfan** [comment]
> I always thought this was an intended mechanic as a means to scale the game difficulty.

> That's my thoughts too.

Ah, I didn't see it that way before, the difficulty level makes a lot of sense actually :)

**Comment by Raildex** [comment]
In OG TR1, atleast in City of Khamoon they don't explode But afaik its actually because the sound and Sprite is missing.
