### ISSUE TITLE
Tomb1Main bug: screen flashes black at the moment a Windows UI element (brightness, volume) appears on the screen and disappears from the screen

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#378]
I tried to record a video of it but it cannot be seen on video. This bug appeared right after updating from 2.4 to 2.5. Still, I'm not sure if it's because of the new release...

I'm playing on full screen. Turning on and off the new Vsync and fade features did not affect the issue.

**Comment by rr-** [comment]
Unfortunately I don't understand the issue.

**Comment by Rapora9** [comment]
> Unfortunately I don't understand the issue.

I will try to record it.

**Comment by Rapora9** [comment]
Sorry about the very low quality. I could not record it via any other way but filming the screen with my phone. As you can see, every time I adjust volume, the screen flashes 2 times: once when the volume icon appears, and once when it disappears. This same happens with brightness setting too. Framerate might drop to as low as 22 from 30 when this flash happens.

https://user-images.githubusercontent.com/97730054/151859420-8e2f3665-998c-4817-bf3a-b6afdd7f5216.mp4

**Comment by Rapora9** [comment]
Found out more about the issue. Might be on my side because even after going back to 2.4, the issue persists.

It goes away if I play on windowed mode, so only happens on full screen.

**Comment by Richard-L** [comment]
Does look odd, I don't have this issue. Is it to do with your monitor by any chance? You could try to OBS capture the issue.

**Comment by Rapora9** [comment]
Changing a setting from "Automatic" to "Nvidia" in 3D settings in Nvidia control panel fixed the issue. Sorry and thank you.
