### ISSUE TITLE
OG bugfix: Sliding on water surface with sidestep buttons makes Lara unexpectedly move forward a bit

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#38]
Happens also with new controls (with Walk button)

**Comment by rr-** [comment]
I'm not sure I understand. Can you please post a video of this?

**Comment by Defrago** [comment]
Video: https://youtu.be/3awwNJeKR4U

**Comment by rr-** [comment]
Nice find although it's a feature, not a bug IMO. It's like when Lara moves a bit forward when she jumps in place.

**Comment by rr-** [comment]
It's a fault of Lara's animations, nothing we can fix from the code. I'd say it's such a miniscule thing that it's not worth fixing.
