### ISSUE TITLE
Feature: allow PS1 FMV native asset playback

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#384]
Allow me to capture this in an issue. We'd talked about it on Discord once before. It would be lovely if the `.FMV` files from the PS1 discs could be used by TR1M. They are the highest quality source for them we have.

You can download them from XProger's files: http://xproger.info/projects/OpenLara/files/TR1_data.7z

**Comment by rr-** [comment]
Oh, aren't they working already? Provided you change the paths to the movies in the gameflow file, that is.

**Comment by Richard-L** [comment]
Oh sorry I wasn't aware. Edited the JSON and they work perfectly. Only curiosity is that `core.avi` is called `corelogo.fmv` in the PS1 asset, so that was an additional small hiccup.

Perhaps then should we rename this (or make a new issue) for deriving the "fall back" procedure of TR1M's FMV choice based on what it finds in `\FMV`?

I would suggest: **PS1 `.FMV` > PC `.RPL` > Custom**
^ where beyond this default they can be re-prioritised by the user, and any custom assets like fan transcodes or upscales need to be delineated clearly.

**Comment by rr-** [comment]
Yeah unfortunately we can't detect corelogo.fmv, the autodetection system only works with file extensions.
I'm not sure how to make it work reliably. Maybe a list of files instead of a single file to try in order of importance?
Wouldn't it be bloatware though?

**Comment by Richard-L** [comment]
I'm not sure I follow. What would be bloatware?

I'm going to link #402 here since this is about "asset choice".

**Comment by rr-** [comment]
Hardcoding a list of different filenames to try in the gameflow file instead of just going through a list of universal file extensions. IMO that's a [feature creep](https://en.wikipedia.org/wiki/Feature_creep)

**Comment by Richard-L** [comment]
If you were going for strict native assets you would have three FMV extensions: `.RPL`, `.FMV` and `.CPK`.

If you added transcodes by fans or GOG/Steam (as is already the case), you have `.AVI`.

Then every now and then someone will try their hand at upscales with the latest en vogue upscaler (currently "Topaz"), and you get whatever is the fashionable media container. As of the past couple of years `.MP4`.

My suggestion would be go after the native ones first, and perhaps include `.AVI`, and then via configurator allow people to assign custom FMVs.

Or, you ship TR1M with your favourite custom FMVs, as you've begun doing with image assets. For videos this would of course drastically increase file size, and as with all custom content it's hard to please everyone.

**Comment by rr-** [comment]
I mean we already do the thing you suggested, we do guess extensions in order of preference. But we do not guess filenames, so if core.fmv is named corelogo.avi elsewhere, we have currently no way to detect that other than adding a list of filenames to check in order.

We won't be shipping FMVs, since they're way too large :) We can add an external download for them like we do with music though.

**Comment by Richard-L** [comment]
All makes good sense.

Would you identify assets at hand of MD5 hashes?

**Comment by rr-** [comment]
If I understand correctly, I think that would be even less flexible since we'd be unable to support fanmade upscales without teaching people about MD5s.

**Comment by Richard-L** [comment]
Sorry I meant only for native assets, not "custom" ones, ie fan procedures.

**Comment by Richard-L** [comment]
@rr- Does this issue still serve any purpose? If it's about asset allocation, I would say we discuss in #402 , or a new (smaller) discussion :wink:
