### ISSUE TITLE
Feature Request: Add death count to level statistics

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#388]
Would it be possible to add player death count to the level statistics? I think it would be interesting to see this information.

I'm not sure if this should be added to #362 or be its own.

**Comment by rr-** [comment]
I think this can be a separate ticket.

**Comment by Richard-L** [comment]
Interesting idea. Would you want to include the total death counts up to the position in the run? Or just have it reset per level, and include a total deaths in a potential final stats screen?

**Comment by Rapora9** [comment]
Hmm, both have their plus sides. Originally I thought that it would reset every level. But maybe it would be better to keep counting between levels? I don't really know. "Deaths per level / total: x/y" would have both but be messy.

**Comment by rr-** [comment]
I would reset it between levels and sum all of it (requires #277) in the endgame screen to be consistent with pickups and kills.

**Comment by Richard-L** [comment]
Agree with both of you. Both are interesting, but to have permanently would be a bit too much. So to just include in the end screen seems right. Let me reference #385 thus.

**Comment by Rapora9** [comment]
> I would reset it between levels and sum all of it (requires #277) in the endgame screen to be consistent with pickups and kills.

The consistency is a good point, seals this for me.

**Comment by rr-** [comment]
Actually I don't know how to implement this.

1. Play the game, let's say my death counter loaded from the save is 3
2. Save in Vilca
3. Continue playing
4. Save in Qualopec
5. Die. Death count += 1.

Here's where the problems begin:

6. Reload in Qualopec. Does the death counter say 3 or 4? I'd say 4, which is logical.
7. But if I were to reload in Vilca instead, does the death counter say 3 or 4?
8. What happens if I load in Qualopec but change my mind and reload in Vilca afterwards?
9. What happens if I load in Qualopec, die again, and choose to go back to Vilca? Does it keep track my Qualopec death? If yes, _how_?
9. What happens if I go to the title menu, and then do any of the scenarios above?
10. What happens if I start a new game, die, save in Caves, start a new game, die in Lost Valley and reload Caves? Does it keep track of my Caves and Lost Valley deaths even though they technically belong to different playthroughs? How do I tell them apart?

**Comment by Rapora9** [comment]
Maybe I'm not understanding something here... Your explanation sounds like the death count did not reset between levels even though we agreed it should reset – unless you're talking about the total sum that is shown in the final game stats screen.

So, can't the death count work similarly to how for example kill count works? It is level-specific and game session -specific, and at the end (well I don't know how it actually works) all the death counts from that game session are parsed from the level stats and added together?

**Comment by Richard-L** [comment]
I'm also mildly confused, but it looks to me as though the question is whether you want to "go back in time" to a specific moment of the "current run", or whether you want to count total overall deaths, regardless of any state loading. Would seem like two different modes to me.

Personally I'm more in favour of the time travel approach, as we do the same with all other stats and states, no?

I do know though that some games do in fact count overall deaths like you say, and thus disallow you to "cheat" a lower death count on a completion screen, achieved by numerous loading after failed game manoeuvres.

**Comment by Rapora9** [comment]
> Personally I'm more in favour of the time travel approach, as we do the same with all other stats and states, no?
> 
> I do know though that some games do in fact count overall deaths like you say, and thus disallow you to "cheat" a lower death count on a completion screen, achieved by numerous loading after failed game manoeuvres.

Wait. I think I understand my misunderstanding now. Every time you die, you have to load from a save, right? Thus, the kill count would stay at 0 if it was resetted from a load.

**Comment by rr-** [comment]
>I think I understand my misunderstanding now. Every time you die, you have to load from a save, right? If the death count acted the same way as e.g. kill count I mentioned, it would reset back to a previous value. The death count would stay at 0 forever because every time it could increase, you have to reload the game to a point where it hasn't increased. Right? 

Exactly this!

**Comment by Richard-L** [comment]
Oh that makes sense okay. Feels a bit hen and egg.

Let me try a take.

>Play the game, let's say my death counter loaded from the save is 3
>Save in Vilca
>Continue playing
>Save in Qualopec
>Die. Death count += 1.
>
>Here's where the problems begin:
>
> 6. Reload in Qualopec. Does the death counter say 3 or 4? I'd say 4, which is logical.

3 if you apply a "deaths per level" window, 4 if you apply a "deaths per run" window.

> 7. But if I were to reload in Vilca instead, does the death counter say 3 or 4?
> 8. What happens if I load in Qualopec but change my mind and reload in Vilca afterwards?

essentially same as above

> 9. What happens if I load in Qualopec, die again, and choose to go back to Vilca? Does it keep track my Qualopec death? If yes, how?

3 deaths per level, 5 deaths in run

> 10. What happens if I go to the title menu, and then do any of the scenarios above?

If you load the same Vilca savestate as in the very beginning, this would identify the run. Thus your per level deaths would be 3, but the per run death count would still be 5. This touches upon run-grouping of savestates, as we had somewhere talked about before. I'm still a little concerned though if this doesn't introduce too much complexity.

> 11. What happens if I start a new game, die, save in Caves, start a new game, die in Lost Valley and reload Caves? Does it keep track of my Caves and Lost Valley deaths even though they technically belong to different playthroughs? How do I tell them apart?

Each time you start a new game, it will create a new run/playthrough, and consequently a savegame group. (I had actually thought once about giving them different font colours in the "load game" dialogue). If you die in Lost Valley and reload Caves, but to reach Lost Valley you had previously chosen "New Game", then this load means it switches the playthrough.

How to tell playthroughs apart other than the initial "New Game" or "New Game +" choice I'm not sure. Would they be enough?

**Comment by rr-** [comment]
TBH this feels like overengineering. Will people even understand the logic behind this?

**Comment by Rapora9** [comment]
Hmm. I don't see any easy way to make this happen so that it both makes sense and cannot be (easily) cheated.

Either each playthrough/run/session has an ID and every time you die in any save of this run, the death count increases.

Or then each save has somehow its own death count and every time you load the save and die, that count increases.

** **

I'm fine with dropping this feature request really, if it would be too complicated and no one else feels strongly about having it.

**Comment by Richard-L** [comment]
I like the idea @Rapora9, but I also thought about letting this sleep perhaps in favour of whatever the devs prioritise 🙏

**Comment by oziphantom** [comment]
Add options to one of the menus. 
"Enable Death Count"
"Reset Death Count"

If you die, +1
If you load from "not the title screen" +1.

It is saved externally from any save files so the value persists across loads, and closing/opening the game.

**Comment by ShadowXJaw724** [comment]
> 

Personally I think that you could make a simple function in the code that simply adds to the death counter for every death on the file. The way i see it work is that whenever you die that value is saved to that specific file like other values such as the coordination, ammo count and such - Which would mean it is exclusively tied to the save and cannot be accessed by any of the other save files.

**Comment by rr-** [comment]
So save just the death count without saving anything else? That might work.
