### ISSUE TITLE
Broken Lara pose at the end of custscene 1

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#390]
When the stats screen is displayed:

![20220202_145030_Cut_Scene_1](https://user-images.githubusercontent.com/81546780/152226538-df5afc72-2aa0-4e39-8ac0-5556a81499d3.jpg)

**Comment by rr-** [comment]
This is regression from 2.5 and is related to my refactor of cinematic loop. The last frame probably reads garbage animation data.

**Comment by atombraiderfan** [comment]
The same thing happens in the Greece ending cutscene:

![20220203_081005_Cut_Scene_2](https://user-images.githubusercontent.com/94776985/152305174-c0fd0e15-69b3-49eb-972b-2c5945d73e68.jpg)
