### ISSUE TITLE
Feature request: extinguish Lara during DOZY

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#4]
If Lara touches Lava and burns, resurrecting her with DOZY makes fires disappear from time to time and when you move too far from initial burning point, game crashes

![Bug](https://user-images.githubusercontent.com/25227941/109237026-df24a600-77e1-11eb-9263-fdbbd777a1df.png)

[Savegame](https://cdn.discordapp.com/attachments/811974815672959046/814273024530448408/saveati.12)

**Comment by rr-** [comment]
This actually is an OG bug as you can do the same with medpacks. In this ticket, I'll extinguish Lara during DOZY, but I'll make a new ticket to fix the OG flame control.
