### ISSUE TITLE
Odd texture at end of Atlantis cutscene

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#405]
Just noticed this odd texture on the ground. 

![20220206_231229_Cut_Scene_4](https://user-images.githubusercontent.com/4934209/152703676-3cc16107-16ad-4351-9aef-fb8188603c0e.png)

This was when running Tomb1Main-2.5-35-g7286bde

Has to do with the fog setting going too far in TR1M?

**Comment by rr-** [comment]
Yeah, I think it's an OG bug that we don't normally see.

Can someone establish what would be just the right amount of fog to disable this effect?

Reminder that we can set the fog level on a per-level basis in the `draw_distance_fade` key.

**Comment by Richard-L** [comment]
Okay I played around with "draw_distance_max" and "draw_distance_fade", and yet weirder things seem to happen.
![20220207_000942_Cut_Scene_4](https://user-images.githubusercontent.com/4934209/152705499-f572dec2-3410-4db8-88ec-b99d7892ca94.png)
![20220207_000945_Cut_Scene_4](https://user-images.githubusercontent.com/4934209/152705502-c2317622-4e17-40ed-8585-53f25d4d6d5a.png)
![20220207_000945_Cut_Scene_4_2](https://user-images.githubusercontent.com/4934209/152705504-d468693d-02ad-4b32-9369-c8989b5f26eb.png)
^ you can see the lower Natla falls, the more the FMV backdrop moves out. Perhaps due to camera movement.

With different settings for the above two, this happened:
![20220207_000625_Cut_Scene_4](https://user-images.githubusercontent.com/4934209/152705518-3f9ce744-2e5e-4e1f-ac72-b913def32ffb.png)

And you can also see Natla having stopped falling at some point and just lying there in the dark:
![20220207_000627_Cut_Scene_4](https://user-images.githubusercontent.com/4934209/152705534-6469f677-628a-4244-86f5-9105c1d64f94.png)

**Comment by rr-** [comment]
Interesting.

At first I was inclined to think we're not clearing the backbuffer, but that is not the case, `GFX_Context_SwapBuffers` does `glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)` like it should. Plus it would manifest in a different way, more like Thames Wharf in Tomb Raider 3, or old Windows Solitaire games, where moving things around would leave visual "ghosts".

My other hypothesis is that we might be reading an invalid texture and gl might cause such requests to fall back to the FMV buffer.

Not sure if I understood this correctly, but is Natla stopping to fall earlier at shorter draw distances? If that is the case, it's a bit of a problem.

**Comment by rr-** [comment]
Alright the FMV is always rendered whenever we reach the max draw distance. (?)
