### ISSUE TITLE
T1M bug: staying on the passport for too long starts demo

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#410]
Opening the passport should block the demo timer, but it doesn't, and upon loading the game, it starts to play the demo.

I'm not sure if this is present on 2.5.

**Comment by rr-** [comment]
@Richard-L could you please check which version breaks this? I'm pretty sure this is our bug, not OG's.

**Comment by Richard-L** [comment]
@rr- I see this is already closed, so no more testing? I'm trying to make time at night after work to help, but it means I'm not always quick enough :pray:

**Comment by rr-** [comment]
Yeah, let's not waste our resources on this, I'm fairly confident this was a regression from 2.1 :)
