### ISSUE TITLE
OG Bug: flame, lava and water emitters state is not saved: return to default after loading

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#418]
Related to #277.

Flame and lava emitters as well as waterfall mist fall back to their default state after loading a save.

Examples:

- player saves at the middle of the flame obstacle in Palace Midas and then loads the save: the flames turn ON immediately because they're set ON at the beginning of the level.

- player saves and loads after getting the last secret in The Great Pyramid: the flame and lava emitters in the bottom of the previous room turn OFF because they're OFF by default, only turning on when the player triggers them a couple rooms before.

- player saves and loads when by the cogs in Lost Valley. The waterfall mist objects turn OFF because they're OFF by default, turned on when player goes over a trigger before the bridge.

Hopefully the status of these objects could be saved and restored properly.

**Comment by Rapora9** [comment]
@Richard-L In #226 you're saying the lava particles (lava emitter in TE) in Natla's Mines work after a reload. Howevere when I test this location, the emitter is shut off after loading. Are you sure you weren't standing on these activation trigger tiles when saving the game?

![Näyttökuva (272)](https://user-images.githubusercontent.com/97730054/153042475-782f1c1c-4563-4e6d-93d6-e8e77b772fe6.png)

**Comment by walkawayy** [comment]
Is there a reason these need to be triggered like maybe saving memory usage back in 1996? Could we just always leave them on if they have triggers in the level file? Maybe I'm missing flipmap reasons or something.

**Comment by Richard-L** [comment]
@Rapora9 that's hard to remember.... It is possible though. I can try to reproduce it.

@walkawayy I would definitely advise against always keeping them on. I think like you say the chance to introduce unknown problems is quite high. Also in classic TR, walking towards lava and it turning "on" was a certain scare tactic and dialogue between a player input and the level. I would not change this.

**Comment by Richard-L** [comment]
Just to capture on video once what @Rapora9 was saying, alluding to what I'd posted under #226:

https://user-images.githubusercontent.com/4934209/153087247-3a482a8d-4144-4b4e-9824-adb4ac85440f.mp4

- Walk on lava trigger tile to trigger lava, save
- On load, lava will show, not because this is saved, but because it gets instantly retriggered
- Move to non-trigger tile, lava is still active, save
- On load, the lava will be inactive, as you're not on a trigger tile

I think this should be fixed but optional, as it likely has speedrun strat implications.

**Comment by Rapora9** [comment]
@Richard-L @walkawayy I was wrong about certain traps working differently based on the type of trigger. My apologies for misinformation. I was overlooking the fact that it's actually the timer of some triggers that turn the traps off. If the timer is 0, they will stay on until deactivated by something like antipad. If the timer is 1, they deactivate as soon as Lara leaves the trigger.

All those traps that shut off automatically just happened to be pads (by chance?) and I didn't look at the timer.
