### ISSUE TITLE
Bug: Boss unhatched egg save issue (The Great Pyramid)

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#423]
If the player creates a save file as soon as The Great Pyramid level starts, and reloads, the egg of the Giant Atlantean remains unhatched.  This will be noticeable again when Lara returns to the scion room and looks out of the balcony.

![20220209_065927_The_Great_Pyramid](https://user-images.githubusercontent.com/94776985/153182598-ddafda28-0588-4fd0-99e5-6137141b5d1d.jpg)

Save file: [saveati.zip](https://github.com/rr-/Tomb1Main/files/8031887/saveati.zip)

**Comment by Rapora9** [comment]
There's inconsistency in other eggs too. I tested the first eggs in Atlantis. I'm not sure  If I save after the egg is hatched but the mutant is still alive, the egg is whole after I reload. However sometimes reloading again fixes this and the egg is gone. Also if you reload after killing the mutant, the egg is gone.

**Comment by Richard-L** [comment]
Just to capture this in TombATI at the beginning of Atlantis. Notice how mutant egg 2 reappears after load, but mutant egg 1 doesn't.

https://user-images.githubusercontent.com/4934209/153297684-e930a338-72cf-4253-8be0-c32db599334d.mp4
