### ISSUE TITLE
Bug: Pistols are not added to the inventory after Natla's Mines if player did not pick them up

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#424]
In original game, even if you did not pick up the pistols in Natla's Mines, they are automatically added to the inventory in the beginning of Atlantis. This is an intended mechanic to make sure the player has pistols in the last two levels too. See this video of a speedrun played with tombati where the pistols are not collected but then are added to the inventory: https://www.youtube.com/watch?v=i6Am1jdLC7M&t=3037s

However in the current version of Tomb1Main (2.5) the pistols are not added. I don't know for how long this has been an issue in tomb1main. See the video clip: 

https://user-images.githubusercontent.com/97730054/153224025-7f564e54-2256-4991-86a7-445bbcbe4ea0.mp4

(I also played through the level normally, doing everything but collecting the pistols, and they still did not appear in Atlantis. This was to confirm that the issue is not due to level skip cheat.)

**Comment by rr-** [comment]
Each of these are separate issues. Please edit these out of this post, you may repaste the video in each ticket. Having one ticket talk about too many things leads to miscommunication and loss of focus.
