### ISSUE TITLE
Bad inventory and weapon state on legacy save load

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#427]
See these max% run saves from the speedrunning community https://drive.google.com/open?id=1iXAHAB94egdlhagNu_hGMYu85hLGzyNx

Load Natla's Mines, check inventory.

TombATI:

https://user-images.githubusercontent.com/4934209/153296466-c08c19a0-d8ef-4426-a35b-31167a227df0.mp4

TR1M (54-g7b21ad9_level_stats)

https://user-images.githubusercontent.com/4934209/153296585-fcd65d0b-0efe-46c6-98bb-30d155aa364e.mp4

- Pistols equipped on load which weren't equipped in save
- Weapons and pickups are missing

**Comment by rr-** [comment]
Save please?

**Comment by Richard-L** [comment]
See google drive link

**Comment by rr-** [comment]
Natla's Mines but the save is in Atlantis? WTF?

**Comment by rr-** [comment]
I have no idea how this save has even a chance of working. The flags for this level are clearly `1` which means only `available` flag, all guns are zeroed.

```
../src/game/savegame_legacy.c 439 Savegame_Legacy_LoadFromFile level 13 flags=1
```

**Comment by rr-** [comment]
NVM, it's that stupid "current position" special level at the end of the levels array. This holds the valid values.
