### ISSUE TITLE
Feature request: Toggle Lara's weapons damage mode cheat

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#43]
I see it this way: When DOZY is activated, player pressing a button (Roll for example). Game toggles weapon mode and shows a message at the below-right area - *** mode selected

Predefined modes:
• Normal
• New Game+ (damage is lowered by 2x)
• Japanese (damage is raised 2x)
• Instant kill (any shot kills any enemy with 1 hit)

**Comment by rr-** [comment]
Why?

**Comment by Defrago** [comment]
Just an unified way to activate newly added cheats - Dozy + some action. You can choose your own approach of course

**Comment by rr-** [comment]
This ticket is about too many things at once. I added a way to start the game in NG or NG+ mode. I'll add a separate ticket for JP mode.
