### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by foxprite** [rr-/Tomb1Main#435]
As it's configured, it's impossible to know what "New Game+", "Japanese NG" and "Japanese NG+" represent without a bit of trial and error and/or digging around in the change log.
It also felt really odd to have 3 options dedicated to start the game with pre-activated cheats as soon as I tried to play for the first time.

Suggestion: replace the current "Controls" icon with the one used on the PS1 or Saturn versions (which, arguably, might better represent what it's purpose is) and repurpose the "handheld icon" to store Cheats such as "Double Damage", "Give All Weapons" and "Enable unlimited Ammo" in the [Options] sub-menu that is only available while already ingame.

It can also just be connected to the "enable_cheats" toggle. When set to false, this icon won't appear.

The multi new game option still seems useful for a file-togglable "Speedrun" mode that enforces movie skipping, keeps the end level screen locked to a certain number of frames before auto-skipping, and adds a more accurate timer that shows hours, minutes, seconds and milliseconds at all times in the selected corner of the screen with the total and current level times.

**Comment by Richard-L** [comment]
This is quite generic and touches upon too many things at once I think. But it's relevant, which is why I'd posted #402 . The sooner we talk about that the better.

**Comment by rr-** [comment]
Changing the inventory ring objects requires messing with the level data as the objects are stored in .PHD. Since we don't bundle the levels, it's easier said than done.

**Comment by foxprite** [comment]
Had to take some time to get updated on everything already posted by both Richard-L's and rr- before.

The UX was definitely the thing that jumped out to me on first boot, how a few options just seemed to require some intimate knowledge of of project to understand their meaning (JP NG+ and Perspective?) while it lacked things controller configurations or the option to boot straight to the main menu, lock window resizing or keep the game in window mode.

Some options like disabling items also felt redundant or incredibly niche (like disabling pickups when we're not forced go grab the items in the first place), but at least those were relegated to an external file, even if it does add additional clutter to it.
All of this led me to make this kind of first post on the project instead of mentioning stuff like the bottom center health bar isn't really very well centered at all, especially after the good-ol' alt+enter.

Might sound like I'm complaining, but actually, as is, it already feels much closer to the original experience than OpenLara does, and it became my preferred way to enjoy this game, even if Steam did have to give me a little help with setting up the controller for it for now. The movement, lighting and colors feel just right and we can even disable that incredibly smudgy bilinear filtering everywhere, even on the main menu!

Sure, the exe is over 7(!) times larger than OpenLara and it's missing the smoother framerate and the much nicer aiming system that that project has, but it's advantages more than make up for it.

> Changing the inventory ring objects requires messing with the level data as the objects are stored in .PHD. Since we don't bundle the levels, it's easier said than done.

Extremely fair point. Definitely too early in the project for such big changes.
I agree with Richard-L that the ideal answer would be an installer that would scrub the Steam\GOG\Disc version of the game, UB, as well as the Saturn and PlayStation versions of the game for all the assets for conversion, patching and then repack it into something clean and easy to use. I imagine it might not be too tough to build since it doesn't have to be very neat as, lets admit it, only more advanced users are gonna do it, most people are just gonna look for an 'asset repack' as 'computers are hard', but it's still extra work that has to be done by someone.

I'll have to consider a more balanced suggestion for this stage of the project, maybe involving moving all cheats to an in-game menu "hidden" in a less used key like F10.

**Comment by Richard-L** [comment]
Agree on a lot of your points. Mainly the fact of how good this project has become, and that it's the best way to play TR1 now.

Shall we continue in the discussion I'd already opened? Feels more appropriate to me. We could then eventually source individual issues from that.

Oh and on a side note, we _are_ the more advanced users 😉

**Comment by foxprite** [comment]
I will close this issue and move to Discussions for such UX improvements. No point cluttering the Issue list with it when there's a lot more things that need more 'urgent' work.
