### ISSUE TITLE
T1M bug: Small gap at bottom of fade on main menu

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#438]
When fading in/out on the ring menu, the fade effect have a tiny gap at the bottom of the screen.  This seems to happen when using the vanilla pcx backdrop, it doesn't happen when using the fanmade backdrop.

The screenshot below is 1920x1080 but I've wrapped a black border around it to help illustrate the issue.

![1](https://user-images.githubusercontent.com/94776985/153748462-b7017bf3-dbb5-4061-951c-24fefbcb2b01.png)

**Comment by Richard-L** [comment]
Interesting. I have it too. Looks like a 1px line or so that is unaffected by the fade.

**Comment by walkawayy** [comment]
Something I've noticed while investigating the fading. In `Output_DrawScreenFlatQuad` my height and width are 2559 and 1439 instead of 2560x1440. Something in `Picture_ScaleSmart` or somewhere in those calls there must be some rounding error happening.

**Comment by Richard-L** [comment]
Ah, so you could reproduce the 1px line on the right we talked about yesterday?

**Comment by JOHN30011887** [comment]
> This issue I've noticed while investigating the EIDOS pic fading black screen flicker. I have a single white pixel line on the right side of my screen.
> 
> In `Output_DrawScreenFlatQuad` my height and width are 2559 and 1439 instead of 2560x1440. Something in `Picture_ScaleSmart` or somewhere in those calls there must have some rounding error?

I just update with latest version 2.7 and noticed this same bug, the EIDOS png image has a bright line only down the right side of my screen

**Comment by Richard-L** [comment]
@JOHN30011887 yup I notice the same now with v2.7. It looks like a 1px horizontal line at the bottom of the screen is unaffected by any fading.

@walkawayy on your previous built this had been on the right of the screen as a vertical line as we'd found.
