### ISSUE TITLE
Weapons falsely always quipped on level start

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#439]
Guys, first off really want to congratulate you on v2.6. I absolutely love it. This has quickly become such a power project to enjoy TR1 on PC. Please be proud.

One mini thing I noticed when trying out the new build: somehow Lara will now _always_ equip her weapons on the first frame of a level start. You can immediately see it when starting a new game into Caves, or just when finishing a level and starting the next (with or without cheat has the same outcome).

**Comment by rr-** [comment]
How did this happen despite our scrupulous testing of every single pull request?…

**Comment by Richard-L** [comment]
I need builds to test :pray: :sweat_smile:

**Comment by rr-** [comment]
Broken by 0ce19d1eec06a79390340aa5ff11fadb51262166. This is a third or fourth installment of this issue. I hate it.

**Comment by walkawayy** [comment]
I swear I tested this wtf lol.
