### ISSUE TITLE
OG bugfix: water rats seem to be unable to deal any damage in Cistern

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#44]

**Comment by Defrago** [comment]
![Снимок (1)](https://user-images.githubusercontent.com/25227941/110227769-be103380-7f0c-11eb-8532-ed897006cbc9.png)
I can't reproduce this. They damage Lara OK on 0.10 release

**Comment by walkawayy** [comment]
I don't have a way to build and test on m current setup, but I think the VOLE_SWIM case should possibly be changed to match the ALLIGATOR_SWIM case. I'm thinking the if check is never true.
```
case VOLE_SWIM:
    if (info.ahead && (item->touch_bits & RAT_TOUCH)) {
        item->goal_anim_state = VOLE_ATTACK;
    }
```
```
```

**Comment by walkawayy** [comment]
I tested on the latest release 1.2.2 and was not able to reproduce this. The water rats (voles) seem to damage normally.

https://streamable.com/vv9xd5

**Comment by rr-** [comment]
Thanks for verifying this. Closing it, then :)
