### ISSUE TITLE
Demo Mode - does not work properly

### ISSUE THREAD

**Issue by Tadexxx** [rr-/Tomb1Main#440]
Hi
Release 2.6.1

Demo Mode - does not work properly 

Lara doesn't shoot, she doesn't fight wolves or bears ...

Demo 2 - Lara it does not come out of the water at the waterfall ..

**Comment by Richard-L** [comment]
This is related to the draw weapons code.

v2.6.1 fixed it for levels, but in the demos the problem still persists.
