### ISSUE TITLE
Bug: Upon death, the game crashes with an error message

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#442]
This issue was introduced in 2.6.2. It has happened 2 times for me in St. Francis Folly after I fell to death in the tall room, and once for @Richard-L in Cistern, rooms 29–32 (according to trview; the room with slopes and crocodiles  + rat at the bottom), again after falling to death.

This is the error message:

![Näyttökuva (300)](https://user-images.githubusercontent.com/97730054/154755990-6782c1d0-6cdb-4ebd-aaeb-a3ad34cfcb73.png)

Summary of the error message: Assertion failed. File: savegame.c. Line: 425. Expression: savegame_info -> format.

**Comment by Richard-L** [comment]
Thank you @Rapora9.

Indeed I had the same occurrence as described:
![image](https://user-images.githubusercontent.com/4934209/154756586-0ffb209b-d7c5-46d2-b87d-d5cfe1187460.png)

It happened in the very moment you expected the bone cracking sound to play and Lara dying. I haven't been able to reproduce this since, or derive steps for it. Hence I hadn't posted it yet.

**Comment by Rapora9** [comment]
> I haven't been able to reproduce this since, or derive steps for it. Hence I hadn't posted it yet.

Same for me which is why I was hesitant about posting this too, but maybe the error line is enough to figure out the reason for this. I will continue investigating the issue and trying to find some logic behind it.

**Comment by walkawayy** [comment]
Hm so it's related to the death counter.

```
bool Savegame_UpdateDeathCounters(int32_t slot_num, GAME_INFO *game_info)
{
    assert(game_info);
    assert(slot_num >= 0);
    SAVEGAME_INFO *savegame_info = &m_SavegameInfo[slot_num];
    assert(savegame_info->format);
    ...
}
```
Maybe something weird is happening when you load a legacy save and die?

**Comment by Rapora9** [comment]
> Maybe something weird is happening when you load a legacy save and die?

Steps to reproduce: load a legacy save -> save -> die.

No fly cheat used.
