### ISSUE TITLE
Option request: Please make robust level stats configurable

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#447]
Related to #362 

The reason for this request is because I like the mystery of how many kills or pickups there are in levels, as opposed to knowing the total. Just wondering if this request is doable or is it more trouble than it's worth?

**Comment by walkawayy** [comment]
Tomb1Main.json has an option to turn them off.
```
    // Enables showing level stats when selecting compass.
    "enable_compass_stats": false,
```

Or you can not open the compass.

**Comment by atombraiderfan** [comment]
There's been a misunderstanding, sorry I wasn't clear, I was referring to the stats change since 2.6 came out.

![20220222_065738_Caves](https://user-images.githubusercontent.com/94776985/155079613-5366df45-1981-48c8-8db9-fe6b4dfbbadc.jpg)

What I'm hoping for is an option to use the vanilla "x" for both kills and pickups instead of "x of y"

**Comment by atombraiderfan** [comment]
I just wanted to say thank you to rr- and walkawayy for working on this feature, and also thank you for everything else because Tomb1Main is awesome.  Keep up the good work! 👍
