### ISSUE TITLE
Issues with memory.c

### ISSUE THREAD

**Issue by oziphantom** [rr-/Tomb1Main#448]
```
void *Memory_Dup(const char *string)
{
    void *memory = Memory_Alloc(strlen(string) + 1);
    strcpy(memory, string);
    return memory;
}
```
A function called *Memory_Dup* that does a string copy? That is a misleading name that could easily cause somebody to call it for binary data, which would end badly. 
It also returns it as `void*`, which hints more that it's for binary data. 
I suggest making it return `char*` and adding String to the name, so its `Memory_DupString` or `Memory_DupStr` just so it's more clear on its function. 

```
void Memory_FreePointer(void *arg)
{
    void *memory;
    memcpy(&memory, arg, sizeof(void *));
    memcpy(arg, &(void *) { NULL }, sizeof(void *));
    Memory_Free(memory);
}
```
Ummm??? I think I see what you are thinking... no. 
So ` memcpy(&memory, arg, sizeof(void *));` this could just be an assign, I get that you want to "make sure you have a proper copy of it" but an assign will do that just fine. Also you don't have to clear the pointer before you do the freeing of memory, this is single threaded from the game allocations perspective so there is no thread race conditions to consider. 
Further more, `memcpy(arg, &(void *) { NULL }, sizeof(void *));` is actually utterly pointless anyway. I guess what you think it is doing is looking up the address of the param passed in from where it was called and setting that to `nullptr` automatically. It doesn't. You are setting the arg that is passed in to now be 0. which is exactly the same as just doing `arg = nullptr`, because `arg` is either a register ( in a release build ) so the memcopy of a `NULL` will just be `mov eax, 0` or some other register or in say a debug build it will be 4 bytes sitting on the stack somewhere. The original pointer is not visible to this function and you can't touch it with it, that would break the promise C makes to you. You can make it `void** arg` and then you will `Memory_Free(&arg); **arg=nullptr`, however you will then need to remember to pass &thing to this function every time. Shame ole C doesn't have pass by reference huh ;) 
Typically we made `#DEFINE` that would call free and then assign the pointer to null for us. 
It is also nice that `Memory_Free` checks for `NULL` first, however this function doesn't so when it goes to `memcpy` from 0 its going to trip the OS memory protection and give you a crash/error etc. And if it didn't by some miracle, the memcpy to it certainly will. 

as an aside and while on the topic of memcpy. 
In s_output.c :167 ( or there abouts my code may differ)
`memcpy(&vertices[1], &vertices[2], left * sizeof(GFX_3D_Vertex));`
memcpy with overlapping regions is "undefined" and crashes when built with clang on windows. For such cases where the is overlap one should use `memmove` which will detect and handle overlap correctly and make sure it copies in the right direction at all times.

**Comment by rr-** [comment]
>Ummm??? I think I see what you are thinking... no.

Improve your communication. This post feels like a rant.

>memcpy(arg, &(void *) { NULL }, sizeof(void *)); is the same as arg = NULL

Empiric evidence says otherwise.

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void Memory_FreePointer(void *arg)
{
    void *memory;
    memcpy(&memory, arg, sizeof(void *));
    memcpy(arg, &(void *) { NULL }, sizeof(void *));
    free(memory);
}

int main(void) {
    void *mem = malloc(1024);
    Memory_FreePointer(&mem);
    printf("%p", mem);
}
```

```
$ gcc ~/test.c -o ~/test -O3 && chmod +x ~/test && ~/test
(nil)
```
Applying your suggestion breaks it.
```
0x559613ba22a0
```

In any case, this idiom was copied from libavcodec which is well tested on many platforms and compilers. If you can convince them to use a better alternative, I may consider a patch.

>change memcpy  to memmove

Fire a pull request.
