### ISSUE TITLE
OG bug: Lara can push a block through a closed door

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#46]
In Atlantis level there is area with a block next to a door. If player cheats Lara to this area (normally you can't get there that early) he can push the block through a door, camera acts weirdly during that. After pusing animation ends, player getting pushed back behind the door

![Снимок (3)](https://user-images.githubusercontent.com/25227941/110209333-0263eb00-7e9d-11eb-953a-a3abc7aa33e8.png)

**Comment by walkawayy** [comment]
Bug video: https://streamable.com/ijztxn
