### ISSUE TITLE
Feature request: Adjust the music symbol position (Sound options)

### ISSUE THREAD

**Issue by aredfan** [rr-/Tomb1Main#468]
I've noticed there's been a few requests to make adjustments to the main menu recently, and I thought it might be a good idea to report this issue as well.  The tip of the music symbol is cut off when highlighted by the gold box.

![1](https://user-images.githubusercontent.com/94776985/157400415-ab2c83d8-8168-4296-8783-6c28de25e384.png)

**Comment by walkawayy** [comment]
The original game sizes aren't consistent. See 8 vs music symbol below. It just naturally sits higher. The issue could be solved by reworking this menu option, but ideally the symbols could be remastered and properly sized.

![image](https://user-images.githubusercontent.com/81546780/157500536-8ccd88f7-22b3-493a-9e67-384c3153baf5.png)

![image](https://user-images.githubusercontent.com/81546780/157500570-0a9a1033-9d21-4941-81ab-7169bf638ed3.png)

**Comment by Richard-L** [comment]
Sometimes these offsets are intentional. I struggle to really see it here but who knows.

While not nice, it seems the occasions of something like the note symbol above are very few. Thus is it feasible to hardcode a custom offset for them to fix this without touching the assets?

**Comment by atombraiderfan** [comment]
Wouldn't using a remastered set of symbols depend on Texture Packs support (#347) getting done first?  All roads lead to Rome :)

I think there should be a vanilla solution too if it's not too much hassle.

**Comment by rr-** [comment]
And #386 which probably will introduce character maps.

**Comment by atombraiderfan** [comment]
I've taken a look at the DOS version, and the music symbol is in front of the gold border instead of behind.  Maybe this is how it should be?

![2](https://user-images.githubusercontent.com/94776985/159471958-b180d7c6-3804-4454-9bca-fe160104201d.jpg)

**Comment by aredfan** [comment]
Closing this ticket because 2.11 fixed the music symbol getting cut off at the top.  Thanks to all involved 👍 

![Capture](https://user-images.githubusercontent.com/94776985/196703983-c9077ada-f586-4319-a3a3-84aa8c598fcd.PNG)
