### ISSUE TITLE
T1M bugfix: Issues with previous saves

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#47]
With 0.10 release loading saves from previous releases creates some bugs. Here is the list of what I can found:

- At Tomb of Tihocan level there is moving blocks with no collision
- At Atlantis and The Great Pyramid levels there is bugged red mummies. Their head is moving but they unable to move or attack Lara

Affected savegames attached

![1](https://user-images.githubusercontent.com/25227941/110215559-7ca36800-7ebb-11eb-87e7-79ee15ed76dd.png)
[BuggedSaveAti.zip](https://github.com/rr-/Tomb1Main/files/6095785/BuggedSaveAti.zip)

**Comment by Defrago** [comment]
Must add that there is no such issues with levels started normally, not from a loaded save

**Comment by rr-** [comment]
After trying to debug this, I really can't locate the error, although I can confirm that the attached files do not work both in T1M 0.10 and vanilla TombATI.

**Comment by rr-** [comment]
Closing for now, in case we stumble upon this issue, I'll reopen this.
