### ISSUE TITLE
Feature request: adjust the item and kill counters for unobtainable items

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#470]
There is a section in the readme that explains that the end of the level counters aren't 100% faithful due to unobtainable items or inaccessible creatures.

That's nice, but I don't think many players will read it. We can do better, which is especially important in the context of the upcoming #469.

I propose to add a delta value in the gameflow for each level, `obtainable_kills` and `obtainable_items`, that defaults to 0, but for the levels with unreachable items, it's set to adjust the values to ones that casual players will understand.

So
Midas: `"unobtainable_items": 1`
Atlantis: `"unobtainable_kills": 4`

Then we could subtract these values during the stats screens.

This way level builders will never have to hardcode their item counts, and we only make an exception to broken levels.

We could also display the total amount in brackets, as in

Midas
ITEMS: 15 (16)

Note that these numbers are completely made up, I didn't look up the actual stats at the time of writing this.

**Comment by Richard-L** [comment]
Why do you think people should be made aware of these items? The only relevance would be for speedruns, where item counts per level established by the community would count.

**Comment by rr-** [comment]
I think you got my message backwards. My goal is to make any extra items that people cannot obtain or often even see without TRView, not appear in the game stats. Or if they need to appear, make it clear that they're not normal items.

**Comment by Richard-L** [comment]
Oh so you want to actively substract those? I think that's a good idea.

But be wary that speedrunners have worked out ways to obtain quite a few of these.
