### ISSUE TITLE
Feature request: restart level feature

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#48]
Relevant TR2M commit: https://github.com/Arsunt/TR2Main/commit/0527c41bf0e2fa17e3d45232ff7c44561426d8aa

**Comment by Richard-L** [comment]
FYI, the PS1 has this custom passport page for it during one of the levels:
![SLES-00024_2021-02-24_23-38-41109075840-fa1beb00-76f9-11eb-89cd-43b7c8d264f2](https://user-images.githubusercontent.com/4934209/137603470-57dd9b0f-b96e-45f1-bf5f-934d558fc11a.png)

I believe the PC assets have it too.

Befittingly during the tutorial, there are no sketches in the passport.
![SLES-00024_2021-03-02_20-44-35](https://user-images.githubusercontent.com/4934209/137603531-2ea34f07-a9b4-4ac2-b4cc-386c7527dc03.png)

**Comment by walkawayy** [comment]
I'm going to take a look at this as an FYI. Not sure if anyone else has or is.

**Comment by oziphantom** [comment]
I hack a basic crack at it, its not as trivial as it sounds sadly. Best of luck.
