### ISSUE TITLE
Kill looped SFX in inventory

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#486]
I noticed this again just now and searched up the related issue for music (#309). Thought I'd separate it into its own issue, based on [this comment](https://github.com/rr-/Tomb1Main/issues/309#issuecomment-1009277547) by rr:

> > Also I did notice that while music and ambient noises pause on the pause screen, stuff like the running water noise near the Lost Valley stream don't pause.
> 
> That's definitely a bug.

What are other looping SFX that aren't music tracks that could be affected by this issue? The lava particle sounds maybe? Burning fire animated sprites?

PS1

https://user-images.githubusercontent.com/4934209/158608468-34b7d120-bedb-4cb9-873a-e225f02559ea.mp4

TR1M

https://user-images.githubusercontent.com/4934209/158608775-19e141d6-ad6e-4aa7-84e8-aeec3456ccd6.mp4

And also another thing I happen to randomly notice as I record this: where is the waterfall splash animation? :thinking: Weridly I've never noticed it missing before. Another issue to separate?

**Comment by walkawayy** [comment]
The SFX not pausing on the pause screen was the bug that was fixed. Pausing SFX on the inventory screen would go with the option to pause music on the inventory screen. There is already an issue for that.

Waterfall splash is a visual effect that is floor triggered. #418 is already open for those effects not reappearing on a reload.

**Comment by rr-** [comment]
So this can be closed since it's covered by other issues?

**Comment by walkawayy** [comment]
I think. I'll update the music issue to mention sound effects too.

**Comment by Richard-L** [comment]
Had a chat with @walkawayy and we agreed to reopen this. The issue of looping SFX (such as the waterfall above) needing to be muted upon inventory open, is still standing.

EDIT: another example is the Scion's wheeling sound you hear near it before shooting it.
