### ISSUE TITLE
T1M bugfix: Tomb1Main.json settings are ignored

### ISSUE THREAD

**Issue by yoqto** [rr-/Tomb1Main#49]
Ever since commit b85e2d34 (I think), `Tomb1Main.json` changes are not applied because the last field value has a comma, breaking JSON parsing. Thus, DOZY can't be used, the FOV for widescreen setups is messed up, etc.

**Comment by Defrago** [comment]
With that comma removed setting are working properly. I agree that attached file have wrong formatting.

**Comment by rr-** [comment]
Thanks for the bug report. That's weird as we're using JSON5 which is supposed to allow that. Since this is the second time I broke the Tomb1Main.json file, I'll add automated unit tests to make sure this doesn't happen again.

**Comment by rr-** [comment]
Actually the settings are working fine. DOZY is not working because cheats are disabled by default, if you overwrite the config after installing the new version, you need to readjust it to your needs.
