### ISSUE TITLE
Pushable blocks on flipmap rooms break

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#496]
First reported by zry-xen in Discord.

According to my tests, this bug was introduced in 2.6 and is still present. The bug is following.

- Player saves the game when FLIPMAP is ON.
- Player loads this save.
- Player turns FLIPMAP OFF.
- Pushable blocks in rooms that flip are now broken. Lara can go through them.

An example of how to replicate the bug: save the game in Tomb of Tihocan at the very beginning (flipmap turns on right when the level starts). Load that save file. Play the game normally, pulling switches and swimming through the long tunnel with a current. At the end of the tunnel there's a room with a rat and a pushable. That pushable is now broken.

Two videos to illustrate the problem:

https://user-images.githubusercontent.com/97730054/159598911-95f7cc41-fa0f-469a-929d-3211ff36f1f1.mp4

https://user-images.githubusercontent.com/97730054/159598918-2ff26079-213d-4d55-ac46-6e5af6b1c047.mp4

**Comment by Rapora9** [comment]
The tall blocks of Qualopec break too. However since they're not in a flip room, this doesn't happen in TR1. But it will happen in custom levels.

Also, if the blocks are broken and flipmaps are turned on again, the blocks seem to take double height (for example Lara stands in the air on top of a movable block, at the height of 2 blocks).

Here is a test level where you can test it out.

[LEVEL1.zip](https://github.com/rr-/Tomb1Main/files/8332613/LEVEL1.zip)

**Comment by rr-** [comment]
Thanks for the test level. I wish all of our bugs were this nicely reported :) It'll be fixed in the upcoming release.

**Comment by Ceelatal** [comment]
I'm glad to hear it was appreciated. Good job tackling the issue :)

**Comment by rr-** [comment]
@walkawayy did you mean to assign me to a code review in the PR?
