### ISSUE TITLE
Unable to pick up certain items underwater with "walk_to_items" enabled

### ISSUE THREAD

**Issue by zry-xen** [rr-/Tomb1Main#500]
Found in: Tomb1Main 2.7+

Enabling walk_to_items causes an issue where some items can't be picked up underwater.

Problematic items: 
- Cistern: Golden key, found beyond the door with spikes beyond that you must first fill with water; 
- Obelisk of Khamoon: 1) Small medkit near the start, after moving the left-most movable block in the room ahead and diving into the far right corner of the outer pool. 2) small medkit and shotgun shells found very close together underwater in the passageway underneath the obelisk (the door of this passageway opening once the four artefacts are collected from the obelisk).

I link a savegame for convenience, and screenshots showing I tried to get as close as possible to the items, from various angles: 
https://mega.nz/folder/1M1FFSTI#qFyujnCsr_LsHgvnOEfigg

**Comment by walkawayy** [comment]
Ok this happens if you pick up consecutive underwater pickups because in TR1, the underwater pickup animation doesn't set `g_Lara.gun_status = LGS_ARMLESS` like TR2 and beyond does.
