### ISSUE TITLE
Change behavior of selected requestor for select level

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#514]
After #494 is merged, the behavior of `REQUEST_INFO` `requested` should be changed. If the user moves to the select level menu, returning back to the load game menu should still have the same savegame selected. Currently, the menu goes back to selecting the newest savegame.

**Comment by rr-** [comment]
@walkawayy do you think we can get this shipped soon?

**Comment by walkawayy** [comment]
Yes I should be able to work on it tomorrow.
