### ISSUE TITLE
Feature: PS1 UI

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#517]
Let's make TR1M even more authentic TR1 vintage shall we. A small thing, but still puzzling why the DOS version got rid of it: the purple hover effect in the UI.

PS1:

![SLES-00024_2022-04-11_23-15-22](https://user-images.githubusercontent.com/4934209/162835555-c104ecc0-3d95-4e68-b0df-52d6db1a02aa.png)

![SLES-00024_2022-04-11_23-15-56](https://user-images.githubusercontent.com/4934209/162835491-3855c43b-bb80-4cb5-b5db-50e77720c142.png)

Saturn:

![image](https://user-images.githubusercontent.com/4934209/162835730-69731f3a-d095-4145-98e6-58acef4ef12a.png)

I would say the PS1 style looks best.

OpenLara has implemented it quite successfully:

![level-select_openlara](https://user-images.githubusercontent.com/4934209/162836023-b359fb95-f110-470f-893e-8feaea67d142.jpg)

**Comment by walkawayy** [comment]
Is there a way to get an accurate RGB purple color value? I have a work in progress version. Also this only applies to the passport menu. Should it apply to the other menu options too?

![image](https://user-images.githubusercontent.com/81546780/163305126-737e5853-67d2-43ca-97bc-9ba6226363bf.png)

**Comment by Richard-L** [comment]
Okay so what I'm eyedropping in Photoshop is **#422173** / **H:264 S:0.55 L:0.29**

![image](https://user-images.githubusercontent.com/4934209/163459897-06db9141-f375-41c3-99a5-54267318c2ae.png)

![image](https://user-images.githubusercontent.com/4934209/163459928-21ea2c30-57c7-4340-b699-5efe7deaa3f9.png)

In Select Level it looks slightly different (worse) which is odd:
![image](https://user-images.githubusercontent.com/4934209/163459959-c2f76fba-80ef-4725-abb7-2b1c0968f838.png)

![image](https://user-images.githubusercontent.com/4934209/163459995-b8469388-8b59-445d-b4c9-cfa4baa977ee.png)

![image](https://user-images.githubusercontent.com/4934209/163460011-30ded1cc-12ad-480e-8f3a-c6b0034d9234.png)

I would go with the look of choosing to load or not.

**Comment by walkawayy** [comment]
Ok thanks I'll test that color out.

Yes the Select Level effect is poorly implemented from bottom left to top right. It's weird because clearly the Load Game option existed.

**Comment by walkawayy** [comment]
Attaching a WIP version:
https://streamable.com/imepal

**Comment by walkawayy** [comment]
The PS1 version's passport menu effect is incorrect (goes from bottom left to top right, not centered). So this feature is using the Load Game style from the first post.

Broken PS1 passport version:
![image](https://user-images.githubusercontent.com/81546780/167033638-d23dcda2-74db-44a5-9056-9a1897a04d7c.png)

**Comment by Richard-L** [comment]
Since the discussion about this now also includes the window style of the UI, ie the gradients in the border, the heading style for "Select Level", etc, we thought it adequate to rename this issue accordingly.
