### ISSUE TITLE
Finish naming cleanups

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#521]
I composed a list of remaining functions that need cleanup.

For the functions we tackled so far it was pretty clear where to put them. However the remaining ones give me some trouble. @walkawayy could you please offer your opinion? Maybe Choco could share her insights too.

(I know that while this task may seem pointless to some or even counterproductive, but these renames do help immensely with locating things in the long run and mental bookkeeping, so the decision whether we'll go through with them is not debatable.)

I want to remove `draw.c` because we have tons of specializations all over the place anyway, and the presence of `draw.c` is confusing because the actual drawing happens in `output.c`.

| #  | File     | Current signature                                                              | Suggested file                   | Suggested name                   |
| -- | ---      | ---                                                                            | ---                              | ---                              |
| 1  | `draw.h` | `void Draw_PrintRoomNumStack(void);`                                           | `game/room_draw.c`               | `Room_PrintDrawStack`            |
| 2  | `draw.h` | `void DrawRooms(int16_t current_room);`                                        | `game/room_draw.c`               | `Room_DrawAllRooms`              |
| 3  | `draw.h` | `void GetRoomBounds(int16_t room_num);`                                        | `game/room_draw.c`               | `Room_GetBounds`                 |
| 4  | `draw.h` | `int32_t SetRoomBounds(int16_t *objptr, int16_t room_num, ROOM_INFO *parent);` | `game/room_draw.c`               | `Room_SetBounds`                 |
| 5  | `draw.h` | `void PrintRooms(int16_t room_number);`                                        | `game/room_draw.c`               | `Room_DrawSingleRoom`            |
| 6  | `draw.h` | `void DrawEffect(int16_t fxnum);`                                              | `game/effects.c`                 | `Effect_Draw`                    |
| 7  | `draw.h` | `void DrawSpriteItem(ITEM_INFO *item);`                                        | `game/objects.c`                 | `Object_DrawSprite`              |
| 8  | `draw.h` | `void DrawDummyItem(ITEM_INFO *item);`                                         | `game/objects.c`                 | `Object_DrawDummy`               |
| 9  | `draw.h` | `void DrawPickupItem(ITEM_INFO *item);`                                        | `game/objects.c`                 | `Object_DrawPickup`              |
| 10 | `draw.h` | `void DrawAnimatingItem(ITEM_INFO *item);`                                     | `game/objects.c`                 | `Object_DrawAnimating`           |
| 11 | `draw.h` | `void DrawUnclippedItem(ITEM_INFO *item);`                                     | `game/objects.c`                 | `Object_DrawUnclipped`           |
| 12 | `draw.h` | `void DrawGunFlash(int32_t weapon_type, int32_t clip);`                        | `game/objects/effects/gunshot.c` | `Gun_DrawFlash`                  |
| 13 | `draw.h` | `void CalculateObjectLighting(ITEM_INFO *item, int16_t *frame);`               | `game/output.c`                  | `Output_CalculateObjectLighting` |
| 14 | `draw.h` | `int32_t GetFrames(ITEM_INFO *item, int16_t *frmptr[], int32_t *rate);`        | `game/items_draw.c`?             | `Item_GetFrames`?                |
| 15 | `draw.h` | `int16_t *GetBoundsAccurate(ITEM_INFO *item);`                                 | `game/items_draw.c`?             | `Item_GetBoundsAccurate`?        |
| 16 | `draw.h` | `int16_t *GetBestFrame(ITEM_INFO *item);`                                      | `game/items_draw.c`?             | `Item_GetBestFrame`?             |
| 17 | `draw.h` | `void Draw_DrawScene(bool draw_overlay);`                                      | `game/game_draw.c`               | `Game_DrawScene`                 |
| 18 | `draw.h` | `int32_t Draw_ProcessFrame(void);`                                             | `game/game_draw.c`               | `Game_ProcessFrame`              |
| 19 | `inv.h`  | `int32_t Display_Inventory(int inv_mode);`                                     | `game/inv.c`                     | `Inv_Display`                    |
| 20 | `inv.h`  | `void Construct_Inventory(void);`                                              | `game/inv.c`                     | `Inv_Construct`                  |
| 21 | `inv.h`  | `void SelectMeshes(INVENTORY_ITEM *inv_item);`                                 | `game/inv.c`                     | `Inv_SelectMeshes`               |
| 22 | `inv.h`  | `bool AnimateInventoryItem(INVENTORY_ITEM *inv_item);`                         | `game/inv.c`                     | `Inv_AnimateItem`                |
| 23 | `inv.h`  | `void DrawInventoryItem(INVENTORY_ITEM *inv_item);`                            | `game/inv.c`                     | `Inv_DrawItem`                   |
| 24 | `inv.h`  | `void RingIsOpen(RING_INFO *ring);`                                            | `game/inv.c`                     | `Inv_Ring_IsOpen`                |
| 25 | `inv.h`  | `void RingIsNotOpen(RING_INFO *ring);`                                         | `game/inv.c`                     | `Inv_Ring_IsNotOpen`             |
| 26 | `inv.h`  | `void RingActive(INVENTORY_ITEM *inv_item);`                                   | `game/inv.c`                     | `Inv_Ring_Active`                |
| 27 | `inv.h`  | `void RingNotActive(void);`                                                    | `game/inv.c`                     | `Inv_Ring_NotActive`             |
| 28 | `inv.h`  | `void RemoveInventoryText(void);`                                              | `game/inv.c`                     | `Inv_RemoveText`                 |

**Comment by rr-** [comment]
This table was made under the assumption that #520 goes through. I suggest we discuss things in increments and as soon as there is consensus about something, I create a PR and clean up the table above.

I think `Requestor` is pretty safe with however first we need to merge #520 .

**Comment by walkawayy** [comment]
Box:
| File          | Current signature                                                                                                                 | Suggested file                    | Suggested name                     |
| ---           | ---                                                                                                                               | ---                               | ---                                |
| `box.h`       | `void InitialiseCreature(int16_t item_num);`                                                                                      | `creature.h`?                     | `Creature_Initialise`?             |
| `box.h`       | `void CreatureAIInfo(ITEM_INFO *item, AI_INFO *info);`                                                                            | `creature.h`?                     | `Creature_AIInfo`?                 |
| `box.h`       | `int32_t SearchLOT(LOT_INFO *LOT, int32_t expansion);`                                                                            | `target.h`                                 | `Target_SearchLOT`                                  |
| `box.h`       | `int32_t UpdateLOT(LOT_INFO *LOT, int32_t expansion);`                                                                            | `target.h`                                 | `Target_UpdateLOT`                                  |
| `box.h`       | `void TargetBox(LOT_INFO *LOT, int16_t box_number);`                                                                              | `target.h`                                 | `Target_Box`                                  |
| `box.h`       | `int32_t StalkBox(ITEM_INFO *item, int16_t box_number);`                                                                          | `target.h`                                 | `Target_StalkBox`                                  |
| `box.h`       | `int32_t EscapeBox(ITEM_INFO *item, int16_t box_number);`                                                                         | `creature.h`                                 | `bool Creature_TestEscapeBox`                                  |
| `box.h`       | `int32_t ValidBox(ITEM_INFO *item, int16_t zone_number, int16_t box_number);`                                                     | `creature.h`                                 | `bool Creature_TestValidBox `            |
| `box.h`       | `void CreatureMood(ITEM_INFO *item, AI_INFO *info, int32_t violent);`                                                             | `creature.h`?                     | `Creature_Mood`?                   |
| `box.h`       | `int32_t CalculateTarget(PHD_VECTOR *target, ITEM_INFO *item, LOT_INFO *LOT);`                                                    | `target.h`                                 | `Target_Calculate`                                 |
| `box.h`       | `int32_t CreatureCreature(int16_t item_num);`                                                                                     | `creature.h`?                     | `Creature_CheckOverlap`?           |
| `box.h`       | `int32_t BadFloor(int32_t x, int32_t y, int32_t z, int16_t box_height, int16_t next_height, int16_t room_number, LOT_INFO *LOT);` | `creature.h`                                 | `bool Creature_TestBadFloor`                                  |
| `box.h`       | `int32_t CreatureAnimation(int16_t item_num, int16_t angle, int16_t tilt);`                                                       | `creature.h`?                     | `Creature_Animation`?              |
| `box.h`       | `int16_t CreatureTurn(ITEM_INFO *item, int16_t maximum_turn);`                                                                    | `creature.h`?                     | `Creature_Turn`?                   |
| `box.h`       | `void CreatureTilt(ITEM_INFO *item, int16_t angle);`                                                                              | `creature.h`?                     | `CreatureTilt`?                    |
| `box.h`       | `void CreatureHead(ITEM_INFO *item, int16_t required);`                                                                           | `creature.h`?                     | `CreatureHead`?                    |
| `box.h`       | `int16_t CreatureEffect(ITEM_INFO *item, BITE_INFO *bite, int16_t (*spawn)());`                                                   | `creature.h`?                     | `CreatureEffect`?                  |

**Comment by fluxtom** [comment]
Not sure if this should have an entire issue made about it, seems me to relate to this issue a bit..

[Savegame_LoadPostrocess](https://github.com/rr-/Tomb1Main/blob/db9c32c7f2fd41cb2fff1a5ba4fee7a8280267ac/src/game/savegame.c#L65) is clearly misspelt, should be `Savegame_LoadPostProcess`.

I can make an entire issue & PR if you think that is reasonable.

**Comment by rr-** [comment]
Yes, go ahead @fluxtom :)

**Comment by walkawayy** [comment]
I think I already fixed it in #494. It's not merged yet though.

**Comment by fluxtom** [comment]
Seems to be :+1:
