### ISSUE TITLE
Restore Lost Valley broken bridge tiles

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#523]
TombATI/TR1M
![20220421_214939_Lost_Valley](https://user-images.githubusercontent.com/4934209/164548360-dc31720b-28f3-490a-a11d-e1ff066596f1.png)

PS1
![SLES-00024_2022-04-21_22-36-52](https://user-images.githubusercontent.com/4934209/164548447-c5870949-76bb-47f5-a025-514e8c695869.png)
![SLES-00024_2022-04-21_22-37-00](https://user-images.githubusercontent.com/4934209/164548518-dac351e5-7431-4849-b8de-92af2f86078e.png)

**Comment by atombraiderfan** [comment]
Good spot Richard, here's a picture from the DOS version that shows the bridge tiles are present.

![Capture](https://user-images.githubusercontent.com/94776985/164911307-3aa15437-ead3-46b6-a666-6731c53d383f.PNG)

Picture from this [video](https://youtu.be/EC_8ljpgySM?t=4299).

**Comment by rr-** [comment]
Does anyone know what's the cause of this and/or how to fix it?

**Comment by Richard-L** [comment]
I think it might be similar to the bats? Tried to record it for you, but it's a bit camera shy. The tiles seem to glitch-appear a little when the camera moves faster. Hope this helps:

https://user-images.githubusercontent.com/4934209/166338914-d0f62f64-8199-479d-878b-ac683060c991.mp4




https://user-images.githubusercontent.com/4934209/166338993-10157ace-8dc5-4ecf-a3ed-2fa27375084f.mp4
