### ISSUE TITLE
Adding a choice for Pierre spawning logic

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#532]
Explaining #530 .

At the moment, having multiple Pierres in a level works as you see in this video:

https://user-images.githubusercontent.com/97730054/166028955-4c923774-ac69-4324-af23-c809436a133d.mp4

Explanation: When an active runaway Pierre already exists and the player triggers a new runaway Pierre, this new Pierre will immediately be gone, while the active Pierre remains. So if the player does not get rid of the active Pierre before trying to trigger a new one, they won't see the new Pierre anywhere. An exception for this is a killable (one-shot) Pierre. If the triggered Pierre is one-shot, then an already active runaway Pierre will disappear instead. This can happen with the 2 Pierres of Tomb of Tihocan (1st runaway, 2nd killable).

** **

This Pierre behaviour is ideal for speedrunners and challenge runners, because they don't then necessarily have to deal with multiple Pierres. However, because the player won't necessarily meet all the Pierres a level has to offer, their experience may be lacking. This is true for original TR1 levels, and also for custom levels where the builder might want to approach things differently than what Core did.

That's why I'm suggesting a choice for how Pierres spawn. The changed logic can be seen in this video:

https://user-images.githubusercontent.com/97730054/166055215-0debdf3d-453f-4abd-9f74-84d00ce79c3f.mp4

Explanation: If an active runaway Pierre already exists and the player triggers a new runaway Pierre, this new Pierre will preserve, while the old Pierre disappears. This way the player will meet all instances of Pierres in the level even if they don't fight them. Of course an exception is again made for killable Pierre: if the active Pierre is killable, he won't disappear, and the freshly triggered runaway Pierre will be gone instead.

**Comment by Rapora9** [comment]
@rr- None of the proposed Pierre code is in 2.8 yet, right?

Asking because Pierre is broken in 2.8. **If you activate him for example in St. Francis Folly and don't shoot him, he does not appear the second time in that level (as it's supposed to be in OG) BUT he also does not appear in any other level either. Only the killable Pierre appears in Tomb of Tihocan.** And if you then complete the game and start a new game, none of the runaway Pierres appear in the whole game, not even once. If you close the game and then start a new one, Pierre again acts like explained in bold.

So if this is not because of my Pierre code, I suspect it has something to do with the level change thing.

**Comment by rr-** [comment]
>EDIT: Based on some more testing with a 2.7 dev build for level change I can say that yes, the level change breaks Pierre appearances. Should a new issue be made for this?

Yes.

**Comment by rr-** [comment]
Let's wait for the hotfix that fixes Pierre first :)

**Comment by rr-** [comment]
Fix published @Rapora9

**Comment by walkawayy** [comment]
I published a test build in Discord. I haven't got a chance to test myself yet and haven't heard back on it yet.

**Comment by Rapora9** [comment]
Something is not right. In the test build Pierre always acts like the JSON setting was `true` (new Pierre remains, old disappears). It worked before.

The fix for Pierre (level select thing) is correct according to my testing, but could it somehow interact with this Pierre change?


EDIT: I am an idiot. I had the "change_pierre_spawn" commented out so it was not being read and default "true" was used. Testing continues...

**Comment by Rapora9** [comment]
Alright, now that the user error is gone, so far everything is working as intended.

**Comment by rr-** [comment]
Merged in https://github.com/rr-/Tomb1Main/commit/3ccd892934e41bfb8c42add08f9a070892f0558a
