### ISSUE TITLE
Blocks no longer push-/pullable on legacy saves in v2.8

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#536]
As @walkawayy had already found from someone posting on [TRF](https://www.tombraiderforums.com/showpost.php?p=8354495&postcount=271), it seems you can now no longer push or pull blocks when the loaded game stems from a legacy save.

1. Load a legacy save
2. Try to move a block

https://user-images.githubusercontent.com/4934209/166839142-fae2e449-da99-4291-847b-0a337388860e.mp4

Possible regression of #496 ?

**Comment by walkawayy** [comment]
`Savegame_PreprocessItems` gets called in `Savegame_Legacy_NeedsBaconLaraFix` before `FlipMap`. Maybe `Savegame_LoadPostprocess` should be called at the end of `Savegame_Legacy_NeedsBaconLaraFix` but that also does stuff like `SpawnItem`. I am not totally up to date on the flipmap code.

**Comment by rr-** [comment]
Fixed in #537
