### ISSUE TITLE
T1M bugfix: TombATI_HQ_FMVs_v1.0 cause crash

### ISSUE THREAD

**Issue by JOHN30011887** [rr-/Tomb1Main#78]
Installing the TombATI_HQ_FMVs_v1.0 causes crash after the first eidos interactive screen

Is it not supported yet?

I had clean steam install of tomb raider 1, installed TombATI_v1.7 and applied your files ontop
The TombATI_HQ_FMVs_v1.0 only installed 10 movie files to the fmv folder, they work without Tomb1Main

**Comment by rr-** [comment]
They're not supported yet but thanks for opening this issue. I'll try to fix them independently of #57 but no promises there.

**Comment by JOHN30011887** [comment]
oh ok, thanks :)

**Comment by rr-** [comment]
For HQ FMV support, we need #57 . But for now I fixed the game crash.
