### ISSUE TITLE
Crashing when starting

### ISSUE THREAD

**Issue by rikiro3764** [rr-/Tomb1Main#96]
so whenever i try to start the game a black bar appears and the game crashes in five seconds. Please tell me how to fix it.

**Comment by Defrago** [comment]
Make sure you have TombATI v1.7 installed previously. Older DLL files are incompatible with Tomb1Main

**Comment by rikiro3764** [comment]
> Make sure you have TombATI v1.7 installed previously. Older DLL files are incompatible with Tomb1Main

well
