### ISSUE TITLE
T1M bugfix: Binding cheat keys to another buttons doesn't suppress default binds

### ISSUE THREAD

**Issue by Defrago** [rr-/Tomb1Main#98]
I have Cheats keys bound to non-default buttons and it just makes more buttons to activate cheats. Default bindings for Items and Level skip cheats (X and I buttons) still working when User Keys is bound.

![Снимок (1)](https://user-images.githubusercontent.com/25227941/112138864-13259800-8be3-11eb-9f2d-222086a501c4.png)

**Comment by rr-** [comment]
This is how the keyboard binding works, it's not just specific to cheat buttons.

**Comment by Defrago** [comment]
Found a workaround then. Bound X and I buttons for Step Left and Step Right and now I don't accidentaly activate those cheats.
